/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PanelBuscar.java
 *
 * Created on 14-02-2011, 01:42:47 PM
 */

package org.jc.swing.find;

import javax.swing.JComboBox;
import javax.swing.JTextField;

/**
 *
 * @author sergio
 */
public class PanelFind extends javax.swing.JPanel {

    /** Creates new form PanelBuscar */
    public PanelFind() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        lBuscar = new javax.swing.JLabel();
        cbOption = new javax.swing.JComboBox();
        tfBuscar = new javax.swing.JTextField();

        setPreferredSize(new java.awt.Dimension(498, 20));
        setRequestFocusEnabled(false);
        setLayout(new java.awt.GridBagLayout());

        lBuscar.setText("Buscar:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 20);
        add(lBuscar, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 79;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        add(cbOption, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 360;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        add(tfBuscar, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    public JComboBox getCbOption() {
        return cbOption;
    }

    public JTextField getTfBuscar() {
        return tfBuscar;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cbOption;
    private javax.swing.JLabel lBuscar;
    private javax.swing.JTextField tfBuscar;
    // End of variables declaration//GEN-END:variables

}
