/*
 * ShowComponents.java
 *
 * Created on 15 ќкт€брь 2006 г., 12:20
 */

package datechooser.demo.steps;

import datechooser.autorun.Configurator;
import static datechooser.demo.locale.DemoBundle.getLocaleString;
import datechooser.beans.*;
import datechooser.demo.Demo;
import java.awt.*;
import java.beans.IntrospectionException;
import javax.swing.JFrame;
import javax.swing.UIManager;
import javax.swing.plaf.PanelUI;
/**
 *
 * @author  Vadik
 */
public class ShowExit extends DemoPanel {
    
    /** Creates new form ShowComponents */
    public ShowExit() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jPanel1 = new javax.swing.JPanel();
        startConfigurator = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        startConfigurator.setSelected(true);
        startConfigurator.setText("jCheckBox1");
        startConfigurator.setText(getLocaleString("StartConfigurator"));
        startConfigurator.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        startConfigurator.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jPanel1.add(startConfigurator);

        add(jPanel1, java.awt.BorderLayout.SOUTH);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/datechooser/demo/steps/thumbsup.gif")));
        jLabel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 30, 1, 1));
        add(jLabel1, java.awt.BorderLayout.CENTER);

    }// </editor-fold>//GEN-END:initComponents
    
    public int getStepCount() {
        return 2;
    }
    
    public String getText() {
        return getLocaleString("sayPaneExit_" + (getCurrentStep() + 1));
    }
    
    public void play() {
        if ((getCurrentStep() == getStepCount() - 1) && startConfigurator.isSelected()) {
            Demo demo = Demo.getInstance();
            demo.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            Configurator config = new Configurator();
            config.start(false);
            demo.setVisible(false);
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JCheckBox startConfigurator;
    // End of variables declaration//GEN-END:variables
    
}
