/*
 * ShowComponents.java
 *
 * Created on 15 ќкт€брь 2006 г., 12:20
 */

package datechooser.demo.steps;

import static datechooser.demo.locale.DemoBundle.getLocaleString;
import datechooser.beans.*;
import datechooser.demo.Demo;
import java.awt.*;
import javax.swing.UIManager;
import javax.swing.plaf.PanelUI;
/**
 *
 * @author  Vadik
 */
public class Show4Permanent extends DemoPanel {
    
    /** Creates new form ShowComponents */
    public Show4Permanent() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jLabel1 = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        jLabel1.setText("<html> <FONT SIZE=\"3\"><FONT COLOR=\"#0000FF\">DateChooserDialog</FONT> dialogBean  = new <B>DateChooserDialog</B>();<BR><FONT COLOR=\"#0000FF\">File</FONT> fromFile = new <B>File</B>(Main.class.<B>getResource</B>(\"Parameters.dchd\").<B>getFile</B>());<BR><FONT COLOR=\"#CC0033\">PermanentBean.<B>loadBeanParameters</B>(dialogBean, fromFile);</FONT><BR>dialogBean.<B>showDialog</B>(null);<BR>//...<BR><I><FONT COLOR=\"#0000FF\">InputStream</FONT> inStream = Main.class.<B>getResource</B>(\"Parameters.dchd\").<B>openStream</B>();<BR><FONT COLOR=\"#CC0033\">PermanentBean.<B>loadBeanParameters</B>(dialogBean, inStream)</FONT>;</I><BR></FONT>\n");
        jLabel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        add(jLabel1, java.awt.BorderLayout.CENTER);

    }// </editor-fold>//GEN-END:initComponents

    public int getStepCount() {
        return 1;
    }

    public String getText() {
        return getLocaleString("sayPane4_" + (getCurrentStep() + 1));
    }

    public void play() {
    }
                    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
    
}
