/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view.configuracion;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JTextField;
import model.domain.Entidad;
import org.jc.swing.CoolButton;
import org.jdesktop.swingx.JXHeader;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;
import utils.IconUI;
import view.ViewMain;
import view.common.CommonForm;

/**
 * EntidadForm
 *
 * @author Sergio Antonio Ochoa Martinez gnu.java.sergio@gmail.com
 * @version 0.1
 */
public final class EntidadForm extends javax.swing.JPanel implements CommonForm {

    private Entidad entidad;
    private CtrlEntidadForm ctrlEntidadForm;
    private DefaultComboBoxModel comboBoxModelEntidad;

    /**
     * Entidad
     */
    public EntidadForm() {
        ctrlEntidadForm = new CtrlEntidadForm();
        initComponents();
    }

    public void initComboBoxEntidad(java.util.List list) {
        comboBoxModelEntidad = new DefaultComboBoxModel();
        comboBoxModelEntidad.removeAllElements();
        for (Object o : list) {
            comboBoxModelEntidad.addElement((Entidad) o);
        }
        cbEntidad.setModel(comboBoxModelEntidad);
    }

    public CoolButton getbGuardar() {
        return bGuardar;
    }

    public CoolButton getbCancelar() {
        return bCancelar;
    }

    public CoolButton getbSelect() {
        return bSelect;
    }

    public JXHeader getHeaderEntidad() {
        return headerEntidad;
    }

    public JComboBox getCbEntidad() {
        return cbEntidad;
    }

    public JCheckBox getCbNuevo() {
        return cbNuevo;
    }    

    public JTextField getTfInstitucion() {
        return tfInstitucion;
    }

    public JTextField getTfNombre() {
        return tfNombre;
    }

    public JTextField getTfSigla() {
        return tfSigla;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        lEntidad = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tfNombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tfSigla = new javax.swing.JTextField();
        tfInstitucion = new javax.swing.JTextField();
        cbEntidad = new javax.swing.JComboBox();
        cbNuevo = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        headerEntidad = new org.jdesktop.swingx.JXHeader();
        jPanel2 = new javax.swing.JPanel();
        bGuardar = new org.jc.swing.CoolButton(0);
        bCancelar = new org.jc.swing.CoolButton(0);
        bSelect = new org.jc.swing.CoolButton(0);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new java.awt.GridBagLayout());

        lEntidad.setText("Entidad:");
        lEntidad.setVisible(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 10);
        jPanel1.add(lEntidad, gridBagConstraints);

        jLabel2.setText("Sigla:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 10);
        jPanel1.add(jLabel2, gridBagConstraints);

        tfNombre.addFocusListener(ctrlEntidadForm);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 300;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 0);
        jPanel1.add(tfNombre, gridBagConstraints);

        jLabel3.setText("Institución:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 10);
        jPanel1.add(jLabel3, gridBagConstraints);

        tfSigla.addFocusListener(ctrlEntidadForm);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 300;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 0);
        jPanel1.add(tfSigla, gridBagConstraints);

        tfInstitucion.addFocusListener(ctrlEntidadForm);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 300;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 0);
        jPanel1.add(tfInstitucion, gridBagConstraints);

        cbEntidad.setVisible(false);
        cbEntidad.addActionListener(ctrlEntidadForm);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 300;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weighty = 1.1;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 0);
        jPanel1.add(cbEntidad, gridBagConstraints);

        cbNuevo.setText("Nuevo");
        cbNuevo.addActionListener(ctrlEntidadForm);
        cbNuevo.setVisible(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        jPanel1.add(cbNuevo, gridBagConstraints);

        jLabel4.setText("Nombre:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 10);
        jPanel1.add(jLabel4, gridBagConstraints);

        headerEntidad.setDescription("");
        headerEntidad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/entidad.png"))); // NOI18N
        headerEntidad.setIconPosition(org.jdesktop.swingx.JXHeader.IconPosition.LEFT);
        headerEntidad.setTitle("Entidad");
        headerEntidad.setTitleFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        bGuardar.setText("Guardar");
        bGuardar.addActionListener(ctrlEntidadForm);
        bGuardar.setIcon(IconUI.getResizableIcon("aceptar", 32, 32));
        jPanel2.add(bGuardar);

        bCancelar.setText("Cancelar");
        bCancelar.addActionListener(ctrlEntidadForm);
        bCancelar.setIcon(IconUI.getResizableIcon("cancelar", 32, 32));
        jPanel2.add(bCancelar);

        bSelect.setText("Seleccionar");
        bSelect.addActionListener(ctrlEntidadForm);
        bSelect.setIcon(IconUI.getResizableIcon("select", 32, 32));
        jPanel2.add(bSelect);
        bSelect.setVisible(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(headerEntidad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 574, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(headerEntidad, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.jc.swing.CoolButton bCancelar;
    private org.jc.swing.CoolButton bGuardar;
    private org.jc.swing.CoolButton bSelect;
    private javax.swing.JComboBox cbEntidad;
    private javax.swing.JCheckBox cbNuevo;
    private org.jdesktop.swingx.JXHeader headerEntidad;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lEntidad;
    private javax.swing.JTextField tfInstitucion;
    private javax.swing.JTextField tfNombre;
    private javax.swing.JTextField tfSigla;
    // End of variables declaration//GEN-END:variables

    @Override
    public Object getObject() {        
        entidad.setNombre(tfNombre.getText());
        entidad.setSigla(tfSigla.getText());
        entidad.setInstitucion(tfInstitucion.getText());
        return entidad;
    }

    @Override
    public void setObject(Object obj) {
        entidad = (Entidad) obj;        
        tfNombre.setText(entidad.getNombre());
        tfSigla.setText(entidad.getSigla());
        tfInstitucion.setText(entidad.getInstitucion());
    }

    private class CtrlEntidadForm implements ActionListener, FocusListener {

        @Override
        public void actionPerformed(ActionEvent e) {
            Object aux = e.getSource();
            if (aux.equals(bGuardar)) {
                entidad = (Entidad) getObject();
                if (bGuardar.getText().equals("Guardar")) {
                    ViewMain.DAO.add(entidad);
                } else {
                    ViewMain.DAO.update(EntidadForm.this.entidad);
                }
                EntidadView.entidadView.getEntidadTable().reload();
                ViewMain.viewMain.getCommonDialog().dispose();
            } else if (aux.equals(bCancelar)) {
                ViewMain.viewMain.getCommonDialog().dispose();
            } else if (aux.equals(cbEntidad)) {
                setObject((Entidad) cbEntidad.getSelectedItem());
            } else if (aux.equals(cbNuevo)) {                
                tfNombre.setEditable(true);
                tfSigla.setEditable(true);
                tfInstitucion.setEditable(true);
                setObject(new Entidad());
            } else if (aux.equals(bSelect)) {
                if (cbNuevo.isSelected()) {
                    entidad = (Entidad) getObject();
                    entidad.setEstado(true);
                    ViewMain.DAO.add(entidad);
                } else {
                    entidad = (Entidad) cbEntidad.getSelectedItem();
                    entidad.setEstado(true);
                    ViewMain.DAO.update(entidad);
                }
                ViewMain.viewMain.setSw(true);
                ViewMain.viewMain.getCommonDialog().dispose();
                ViewMain.viewMain.initAplication();
            }
        }

        @Override
        public void focusGained(FocusEvent e) {
            Object aux = e.getSource();
            if (aux.equals(tfInstitucion)) {
                tfInstitucion.selectAll();
            } else if (aux.equals(tfNombre)) {
                tfNombre.selectAll();
            } else if (aux.equals(tfSigla)) {
                tfSigla.selectAll();
            }
        }

        @Override
        public void focusLost(FocusEvent e) {
        }
    }
}
