/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view.configuracion;

import java.awt.BorderLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import model.domain.Entidad;
import model.domain.Unidad;
import org.jc.swing.CoolButton;
import utils.IconUI;
import view.ViewMain;
import view.common.CommonDialog;
import view.common.CommonView;

/**
 * EntidadView
 *
 * @author Sergio Antonio Ochoa Martinez - gnu.java.sergio@gmail.com
 * @version 0.1
 */
public class EntidadView extends javax.swing.JPanel implements CommonView {

    private CtrlEntidadView ctrlEntidadView;
    private EntidadForm entidadForm;
    private EntidadTable entidadTable;
    public static EntidadView entidadView;

    public EntidadView() {
        entidadView = this;
        ctrlEntidadView = new CtrlEntidadView();
        initComponents();
        entidadForm = new EntidadForm();
        entidadTable = new EntidadTable();
        this.add(entidadTable, BorderLayout.CENTER);
    }

    public CoolButton getbDelete() {
        return bDelete;
    }

    public CoolButton getbNew() {
        return bNew;
    }

    public CoolButton getbUpdate() {
        return bUpdate;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        bNew = new org.jc.swing.CoolButton(1);
        bUpdate = new org.jc.swing.CoolButton(2);
        bDelete = new org.jc.swing.CoolButton(2);
        bSelect = new org.jc.swing.CoolButton(2);

        setLayout(new java.awt.BorderLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 0, 5));

        bNew.setText("Nuevo");
        bNew.setIcon(IconUI.getResizableIcon("add", 32,32));
        bNew.addActionListener(ctrlEntidadView);
        jPanel1.add(bNew);

        bUpdate.setText("Editar");
        bUpdate.setIcon(IconUI.getResizableIcon("update", 32, 32));
        jPanel1.add(bUpdate);
        bUpdate.addActionListener(ctrlEntidadView);

        bDelete.setText("Borrar");
        bDelete.setIcon(IconUI.getResizableIcon("delete", 32, 32));
        jPanel1.add(bDelete);
        bDelete.addActionListener(ctrlEntidadView);

        bSelect.setText("Seleccionar");
        bSelect.setIcon(IconUI.getResizableIcon("select", 32, 32));
        jPanel1.add(bSelect);
        bSelect.addActionListener(ctrlEntidadView);

        add(jPanel1, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.jc.swing.CoolButton bDelete;
    private org.jc.swing.CoolButton bNew;
    private org.jc.swing.CoolButton bSelect;
    private org.jc.swing.CoolButton bUpdate;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
  
    public EntidadTable getEntidadTable() {
        return entidadTable;
    }

    @Override
    public void addNew() {
        ViewMain.viewMain.getGlassPane().setVisible(true);
        ViewMain.viewMain.setCommonDialog(new CommonDialog(ViewMain.viewMain, true));        
        entidadForm.setObject(new Entidad());
        entidadForm.getbGuardar().setText("Guardar");
        entidadForm.getHeaderEntidad().setDescription("Introducir los datos de la Entidad");        
        ViewMain.viewMain.getCommonDialog().add(entidadForm);
        ViewMain.viewMain.getCommonDialog().visibleDialog("Nueva Entidad");
        ViewMain.viewMain.getGlassPane().setVisible(false);
    }

    @Override
    public void addUpdate() {
        ViewMain.viewMain.getGlassPane().setVisible(true);
        ViewMain.viewMain.setCommonDialog(new CommonDialog(ViewMain.viewMain, true));
        Entidad entidad = new Entidad();
        entidad = (Entidad) entidadTable.getSelectedObject(entidad);
        if (entidad != null) {
            entidad = (Entidad) ViewMain.DAO.getObject(entidad);
            entidadForm.setObject(entidad);
            entidadForm.getbGuardar().setText("Actualizar");
            entidadForm.getHeaderEntidad().setDescription("Modificar los datos de la Entidad");            
            ViewMain.viewMain.getCommonDialog().add(entidadForm);
            ViewMain.viewMain.getCommonDialog().visibleDialog("Actualizando " + entidad.getNombre());
            ViewMain.viewMain.getGlassPane().setVisible(false);
        } else {
            JOptionPane.showMessageDialog(ViewMain.viewMain, "No selecciono ninguna Entidad", "Mensaje", 0);
            ViewMain.viewMain.getGlassPane().setVisible(false);
        }
    }

    @Override
    public void addDelete() {
        Entidad entidad = new Entidad();
        entidad = (Entidad) entidadTable.getSelectedObject(entidad);
        if (entidad != null) {
            int option = JOptionPane.showConfirmDialog(ViewMain.viewMain, "Esta seguro que desea borrar la Entidad", "Borrar", 0);
            if (option == 0) {
                ViewMain.DAO.delete(entidad);
                entidadTable.reload();
            }
        } else {
            JOptionPane.showMessageDialog(ViewMain.viewMain, "No selecciono ninguna entidad", "Borrar", 0);
        }
    }

    public void addSelect() {
        ViewMain.viewMain.setCommonDialog(new CommonDialog(ViewMain.viewMain, true));
        Entidad entidad = new Entidad();
        entidad = (Entidad) entidadTable.getSelectedObject(entidad);
        if (entidad != null) {
            Entidad entidadEstado = (Entidad) ViewMain.DAO.getObject(new Entidad());
            entidadEstado.setEstado(false);
            ViewMain.DAO.update(entidadEstado);                     
            Unidad unidadEstado = (Unidad) ViewMain.DAO.getObject(new Unidad());
            unidadEstado.setEstado(false);           
            ViewMain.DAO.update(unidadEstado);            
            entidad = (Entidad) ViewMain.DAO.getObject(entidad);
            entidad.setEstado(true);
            ViewMain.DAO.update(entidad);
            ViewMain.viewMain.setSw(true);
            ViewMain.viewMain.initAplication();
            ViewMain.viewMain.getlUnidad().setText("");
            ViewMain.viewMain.getFrontend().hide(ViewMain.viewMain.getDockableOficina());
            ViewMain.viewMain.getFrontend().hide(ViewMain.viewMain.getDockableResponsable());
            ViewMain.viewMain.getFrontend().hide(ViewMain.viewMain.getDockableAuxiliar());
            ViewMain.viewMain.getFrontend().hide(ViewMain.viewMain.getDockableActivoFijo());
        } else {
            JOptionPane.showMessageDialog(ViewMain.viewMain, "No selecciono ninguna Entidad", "Mensaje", 0);
        }
    }
    
    private class CtrlEntidadView implements ActionListener {
        @Override
        public void actionPerformed(ActionEvent e) {
            Object aux = e.getSource();
            if (aux.equals(bNew)) {
                addNew();
            } else if (aux.equals(bUpdate)) {
                addUpdate();
            } else if (aux.equals(bDelete)) {
                addDelete();
            } else if (aux.equals(bSelect)) {
                addSelect();
            }
        }
    }
}
