/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view.configuracion;

import java.awt.BorderLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import model.domain.Unidad;
import org.jc.swing.CoolButton;
import utils.IconUI;
import view.ViewMain;
import view.common.CommonDialog;
import view.common.CommonView;

/**
 * UnidadView
 *
 * @author Sergio Antonio Ochoa Martinez - gnu.java.sergio@gmail.com
 * @version 0.1
 */
public class UnidadView extends javax.swing.JPanel implements CommonView {

    private CtrlUnidadView ctrlUnidadView;
    private UnidadForm unidadForm;
    private UnidadTable unidadTable;
    public static UnidadView unidadView;

    public UnidadView() {
        unidadView = this;
        ctrlUnidadView = new CtrlUnidadView();
        initComponents();
        unidadForm = new UnidadForm();
        unidadTable = new UnidadTable();
        this.add(unidadTable, BorderLayout.CENTER);
    }

    public CoolButton getbDelete() {
        return bDelete;
    }

    public CoolButton getbNew() {
        return bNew;
    }

    public CoolButton getbUpdate() {
        return bUpdate;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        bNew = new org.jc.swing.CoolButton(1);
        bUpdate = new org.jc.swing.CoolButton(2);
        bDelete = new org.jc.swing.CoolButton(2);
        bSelect = new org.jc.swing.CoolButton(2);

        setLayout(new java.awt.BorderLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 0, 5));

        bNew.setText("Nuevo");
        bNew.setIcon(IconUI.getResizableIcon("add", 32,32));
        bNew.addActionListener(ctrlUnidadView);
        jPanel1.add(bNew);

        bUpdate.setText("Editar");
        bUpdate.setIcon(IconUI.getResizableIcon("update", 32, 32));
        jPanel1.add(bUpdate);
        bUpdate.addActionListener(ctrlUnidadView);

        bDelete.setText("Borrar");
        bDelete.setIcon(IconUI.getResizableIcon("delete", 32, 32));
        jPanel1.add(bDelete);
        bDelete.addActionListener(ctrlUnidadView);

        bSelect.setText("Seleccionar");
        bSelect.setIcon(IconUI.getResizableIcon("select", 32, 32));
        jPanel1.add(bSelect);
        bSelect.addActionListener(ctrlUnidadView);

        add(jPanel1, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.jc.swing.CoolButton bDelete;
    private org.jc.swing.CoolButton bNew;
    private org.jc.swing.CoolButton bSelect;
    private org.jc.swing.CoolButton bUpdate;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    public UnidadTable getUnidadTable() {
        return unidadTable;
    }

    @Override
    public void addNew() {
        ViewMain.viewMain.getGlassPane().setVisible(true);
        ViewMain.viewMain.setCommonDialog(new CommonDialog(ViewMain.viewMain, true));
        ViewMain.viewMain.getCommonDialog().setTitle("Nueva Unidad");
        unidadForm.setObject(new Unidad());
        unidadForm.getbGuardar().setText("Guardar");
        unidadForm.getHeaderUnidad().setDescription("Introducir los datos de la Unidad");
        ViewMain.viewMain.getCommonDialog().add(unidadForm);
        ViewMain.viewMain.getCommonDialog().visibleDialog("Nueva Unidad");
        ViewMain.viewMain.getGlassPane().setVisible(false);
    }

    @Override
    public void addUpdate() {
        ViewMain.viewMain.getGlassPane().setVisible(true);
        ViewMain.viewMain.setCommonDialog(new CommonDialog(ViewMain.viewMain, true));
        Unidad unidad = new Unidad();
        unidad = (Unidad) unidadTable.getSelectedObject(unidad);
        if (unidad != null) {
            unidad = (Unidad) ViewMain.DAO.getObject(unidad);
            unidadForm.setObject(unidad);
            unidadForm.getbGuardar().setText("Actualizar");
            unidadForm.getHeaderUnidad().setDescription("Modificar los datos de la Unidad");            
            ViewMain.viewMain.getCommonDialog().add(unidadForm);
            ViewMain.viewMain.getCommonDialog().visibleDialog("Actualizando " + unidad.getDescripcion());
            ViewMain.viewMain.getGlassPane().setVisible(false);
        } else {
            JOptionPane.showMessageDialog(ViewMain.viewMain, "No selecciono ninguna Unidad", "Mensaje", 0);
            ViewMain.viewMain.getGlassPane().setVisible(false);
        }
    }

    @Override
    public void addDelete() {
        Unidad unidad = new Unidad();
        unidad = (Unidad) unidadTable.getSelectedObject(unidad);
        if (unidad != null) {
            int option = JOptionPane.showConfirmDialog(ViewMain.viewMain, "Esta seguro que desea borrar la Unidad", "Borrar", 0);
            if (option == 0) {
                ViewMain.DAO.delete(unidad);
                unidadTable.reload();
            }
        } else {
            JOptionPane.showMessageDialog(ViewMain.viewMain, "No selecciono ninguna unidad", "Borrar", 0);
        }
    }

    public void addSelect() {
        ViewMain.viewMain.setCommonDialog(new CommonDialog(ViewMain.viewMain, true));
        Unidad unidad = new Unidad();
        unidad = (Unidad) unidadTable.getSelectedObject(unidad);
        if (unidad != null) {
            Unidad unidadEstado = (Unidad) ViewMain.DAO.getObject(new Unidad());
            unidadEstado.setEstado(false);
            ViewMain.DAO.update(unidadEstado);
            unidad = (Unidad) ViewMain.DAO.getObject(unidad);
            unidad.setEstado(true);
            ViewMain.DAO.update(unidad);
            ViewMain.viewMain.setUnidad(unidad);
            ViewMain.viewMain.getlUnidad().setText("<html><b>Unidad: </b>" + unidad.getIdUnidad() + "  " + unidad.getDescripcion() + "</b></html>");
            ViewMain.viewMain.getFrontend().hide(ViewMain.viewMain.getDockableOficina());
            ViewMain.viewMain.getFrontend().hide(ViewMain.viewMain.getDockableResponsable());
            ViewMain.viewMain.getFrontend().hide(ViewMain.viewMain.getDockableAuxiliar());
            ViewMain.viewMain.getFrontend().hide(ViewMain.viewMain.getDockableActivoFijo());
            JOptionPane.showMessageDialog(ViewMain.viewMain, "Se cambio la unidad administrativa", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(ViewMain.viewMain, "No selecciono ninguna Unidad", "Mensaje", JOptionPane.ERROR_MESSAGE);
        }
    }

    private class CtrlUnidadView implements ActionListener {

        @Override
        public void actionPerformed(ActionEvent e) {
            Object aux = e.getSource();
            if (aux.equals(bNew)) {
                addNew();
            } else if (aux.equals(bUpdate)) {
                addUpdate();
            } else if (aux.equals(bDelete)) {
                addDelete();
            } else if (aux.equals(bSelect)) {
                addSelect();
            }
        }
    }
}
