package view.activos;

import datechooser.events.SelectionChangedEvent;
import datechooser.events.SelectionChangedListener;
import datechooser.model.multiple.MultyDateChooseModel;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.util.Calendar;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import model.domain.ActivoFijo;
import model.domain.Auxiliar;
import model.domain.Baja;
import model.domain.Configuracion;
import model.domain.Grupo;
import model.domain.Oficina;
import model.domain.Responsable;
import model.domain.Revaluo;
import org.jc.swing.CoolButton;
import org.jdesktop.swingx.JXHeader;
import utils.IconUI;
import view.ViewMain;
import view.administracion.AuxiliarView;
import view.administracion.OficinaView;
import view.administracion.ResponsableView;
import view.common.CommonDialog;
import view.common.CommonForm;

/**
 * ActivoFijoForm
 *
 * @author Sergio Antonio Ochoa Martinez gnu.java.sergio@gmail.com
 * @version 0.2
 */
public class ActivoFijoForm extends javax.swing.JPanel implements CommonForm {

    private ActivoFijo activoFijo;
    private CtrlActivoFijoForm ctrlActivoFijoForm;
    private DefaultComboBoxModel comboBoxModelGrupo;
    private DefaultComboBoxModel comboBoxModelAuxiliar;
    private DefaultComboBoxModel comboBoxModelOficina;
    private DefaultComboBoxModel comboBoxModelResponsable;
    public static ActivoFijoForm activoFijoForm;
    private CommonDialog commonDialog;

    /**
     * ActivoFijo
     */
    public ActivoFijoForm(ActivoFijo activoFijo) {
        this.activoFijo = activoFijo;
        ctrlActivoFijoForm = new CtrlActivoFijoForm();
        activoFijoForm = this;
        initComponents();
    }

    public CoolButton getbGuardar() {
        return bGuardar;
    }

    public void initComboBoxGrupo(java.util.List list) {
        comboBoxModelGrupo = new DefaultComboBoxModel();
        comboBoxModelGrupo.removeAllElements();
        comboBoxModelGrupo.addElement("Seleccione un Grupo");
        for (Object o : list) {
            comboBoxModelGrupo.addElement((Grupo) o);
        }
        cbGrupo.setModel(comboBoxModelGrupo);
    }

    public void initComboBoxOficina(java.util.List list) {
        comboBoxModelOficina = new DefaultComboBoxModel();
        comboBoxModelOficina.removeAllElements();
        comboBoxModelOficina.addElement("Selecione una Oficina");
        for (Object o : list) {
            comboBoxModelOficina.addElement((Oficina) o);
        }
        cbOficina.setModel(comboBoxModelOficina);
    }

    public JXHeader getHeaderActivoFijo() {
        return headerActivoFijo;
    }

    public CommonDialog getCommonDialog() {
        return commonDialog;
    }

    public JTextField getTfCodigo() {
        return tfCodigo;
    }

    public CoolButton getbApiEstado() {
        return bApiEstado;
    }

    public CoolButton getbDuplicate() {
        return bDuplicate;
    }

    public CoolButton getbTransfer() {
        return bTransfer;
    }

    public JComboBox getCbGrupo() {
        return cbGrupo;
    }

    public JComboBox getCbOficina() {
        return cbOficina;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel2 = new javax.swing.JPanel();
        bFirst = new org.jc.swing.CoolButton(1);
        bPrevious = new org.jc.swing.CoolButton(2);
        bNext = new org.jc.swing.CoolButton(2);
        bLast = new org.jc.swing.CoolButton(3);
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tfCodigoADI = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tfCodigo = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        tfIndiveUFV = new javax.swing.JTextField();
        dccIncorporacion = new datechooser.beans.DateChooserCombo();
        jPanel3 = new javax.swing.JPanel();
        spDescripcion = new javax.swing.JScrollPane();
        taDescripcion = new javax.swing.JTextArea();
        cbGrupo = new javax.swing.JComboBox();
        cbAuxiliar = new javax.swing.JComboBox();
        cbOficina = new javax.swing.JComboBox();
        cbResponsable = new javax.swing.JComboBox();
        cbEstado = new javax.swing.JComboBox();
        spObservaciones = new javax.swing.JScrollPane();
        taObservaciones = new javax.swing.JTextArea();
        tfCargo = new javax.swing.JTextField();
        tfRube = new javax.swing.JTextField();
        tfFinanciador = new javax.swing.JTextField();
        tfNumeroConvenio = new javax.swing.JTextField();
        cbDepreciar = new javax.swing.JCheckBox();
        cbActualizar = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lApiEstado = new javax.swing.JLabel();
        bAuxiliar = new org.jc.swing.CoolButton(2);
        bOficina = new org.jc.swing.CoolButton(2);
        bResponsable = new org.jc.swing.CoolButton(2);
        lRevaluo = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        tfCostoInicial = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        tfDepreciacionAcumuladaInicial = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        tfFactorActual = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        tfValor = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        tfDepreciacionAcumulada = new javax.swing.JTextField();
        tfValorNeto = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        tfVidaUtil = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        tfDias = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        tfPorcentajeDepreciacion = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        tfDepreciacionGestion = new javax.swing.JTextField();
        lMensaje = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        bGuardar = new org.jc.swing.CoolButton(0);
        bExit = new org.jc.swing.CoolButton(0);
        bDuplicate = new org.jc.swing.CoolButton(0);
        bTransfer = new org.jc.swing.CoolButton(0);
        bSearch = new org.jc.swing.CoolButton(0);
        bRevaluo = new org.jc.swing.CoolButton(0);
        bBaja = new org.jc.swing.CoolButton(0);
        jPanel4 = new javax.swing.JPanel();
        bApiEstado = new org.jc.swing.CoolButton(2);
        jPanel8 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        tfUFVActual = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        dccToday = new datechooser.beans.DateChooserCombo();
        headerActivoFijo = new org.jdesktop.swingx.JXHeader();

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        bFirst.setText("Primero");
        bFirst.addActionListener(ctrlActivoFijoForm);
        jPanel2.add(bFirst);

        bPrevious.setText("Anterior");
        bPrevious.addActionListener(ctrlActivoFijoForm);
        jPanel2.add(bPrevious);

        bNext.setText("Siguiente");
        bNext.addActionListener(ctrlActivoFijoForm);
        jPanel2.add(bNext);

        bLast.setText("Ultimo");
        bLast.addActionListener(ctrlActivoFijoForm);
        jPanel2.add(bLast);

        setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("Codigo:");

        tfCodigoADI.addFocusListener(ctrlActivoFijoForm);

        jLabel2.setText("Codigo ADI:");

        tfCodigo.addFocusListener(ctrlActivoFijoForm);

        jLabel14.setText("Indice UFV:");

        tfIndiveUFV.addFocusListener(ctrlActivoFijoForm);
        tfIndiveUFV.setEditable(false);

        dccIncorporacion.addSelectionChangedListener(new datechooser.events.SelectionChangedListener() {
            public void onSelectionChange(datechooser.events.SelectionChangedEvent evt) {
                dccIncorporacionOnSelectionChange(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfCodigo, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                    .addComponent(tfCodigoADI))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(dccIncorporacion, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tfIndiveUFV, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(tfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel14)
                        .addComponent(tfIndiveUFV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(dccIncorporacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfCodigoADI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        taDescripcion.setColumns(20);
        taDescripcion.setLineWrap(true);
        taDescripcion.setWrapStyleWord(true);
        taDescripcion.addFocusListener(ctrlActivoFijoForm);
        taDescripcion.setRows(5);
        spDescripcion.setViewportView(taDescripcion);

        cbGrupo.addItemListener(ctrlActivoFijoForm);

        cbAuxiliar.setEnabled(false);

        cbOficina.addItemListener(ctrlActivoFijoForm);

        cbResponsable.setEnabled(false);
        cbResponsable.addItemListener(ctrlActivoFijoForm);

        cbEstado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione", "Bueno", "Regular", "Malo" }));

        taObservaciones.setColumns(20);
        taObservaciones.setRows(5);
        taObservaciones.setLineWrap(true);
        taObservaciones.setWrapStyleWord(true);
        taObservaciones.addFocusListener(ctrlActivoFijoForm);
        spObservaciones.setViewportView(taObservaciones);

        tfCargo.setEnabled(false);

        tfRube.addFocusListener(ctrlActivoFijoForm);

        tfFinanciador.addFocusListener(ctrlActivoFijoForm);

        tfNumeroConvenio.addFocusListener(ctrlActivoFijoForm);

        cbDepreciar.setText("Depreciar");
        cbDepreciar.setEnabled(false);

        cbActualizar.setText("Actualizar");
        cbActualizar.setEnabled(false);

        jLabel8.setText("Estado:");

        jLabel7.setText("Oficina:");

        jLabel6.setText("Responsable:");

        jLabel5.setText("Auxiliar:");

        jLabel4.setText("Grupo:");

        jLabel3.setText("Descripción:");

        jLabel9.setText("Cargo:");

        jLabel10.setText("Rube:");

        jLabel11.setText("ORG. Financiador:");

        jLabel12.setText("NRO. Convenio:");

        jLabel13.setText("Obsercaciones:");

        lApiEstado.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lApiEstado.setForeground(new java.awt.Color(255, 0, 0));
        lApiEstado.setText("ELABORADO");

        bAuxiliar.setToolTipText("Nuevo Auxiliar");
        bAuxiliar.addActionListener(ctrlActivoFijoForm);
        bAuxiliar.setIcon(IconUI.getResizableIcon("add", 16, 16));

        bOficina.setToolTipText("Nueva Oficina");
        bOficina.addActionListener(ctrlActivoFijoForm);
        bOficina.setIcon(IconUI.getResizableIcon("add", 16, 16));

        bResponsable.setToolTipText("Nuevo Responsable");
        bResponsable.addActionListener(ctrlActivoFijoForm);
        bResponsable.setIcon(IconUI.getResizableIcon("add", 16, 16));

        lRevaluo.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lRevaluo.setForeground(new java.awt.Color(0, 51, 255));
        lRevaluo.setText("REVALUO");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel4)
                    .addComponent(jLabel8)
                    .addComponent(jLabel13)
                    .addComponent(jLabel3))
                .addGap(27, 27, 27)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbGrupo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbAuxiliar, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbOficina, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbResponsable, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(spObservaciones, javax.swing.GroupLayout.DEFAULT_SIZE, 379, Short.MAX_VALUE)
                            .addComponent(cbEstado, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(bResponsable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(tfNumeroConvenio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                                            .addComponent(tfFinanciador, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(tfRube, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(tfCargo, javax.swing.GroupLayout.Alignment.TRAILING)))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(55, 55, 55)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lRevaluo)
                                            .addComponent(lApiEstado)))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addComponent(bOficina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addComponent(bAuxiliar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cbDepreciar)
                                .addGap(18, 18, 18)
                                .addComponent(cbActualizar))))
                    .addComponent(spDescripcion))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(spDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cbGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cbActualizar)
                                    .addComponent(cbDepreciar))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(cbAuxiliar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel5))
                                    .addComponent(bAuxiliar, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cbOficina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7)))
                            .addComponent(bOficina, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(lRevaluo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lApiEstado)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbResponsable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(tfCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bResponsable, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(tfRube, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tfFinanciador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tfNumeroConvenio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12)))
                            .addComponent(jLabel13))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(spObservaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel5.setLayout(new java.awt.GridBagLayout());

        tfCostoInicial.addFocusListener(ctrlActivoFijoForm);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 120;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 0);
        jPanel5.add(tfCostoInicial, gridBagConstraints);

        jLabel15.setText("Costo Inicial:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        jPanel5.add(jLabel15, gridBagConstraints);

        tfDepreciacionAcumuladaInicial.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 120;
        jPanel5.add(tfDepreciacionAcumuladaInicial, gridBagConstraints);

        jLabel16.setText("Dep. Acu. Inicial:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        jPanel5.add(jLabel16, gridBagConstraints);

        tfFactorActual.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 120;
        jPanel5.add(tfFactorActual, gridBagConstraints);

        jLabel17.setText("Factor Actual:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        jPanel5.add(jLabel17, gridBagConstraints);

        tfValor.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 120;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 10);
        jPanel5.add(tfValor, gridBagConstraints);

        jLabel18.setText("Valor:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        jPanel5.add(jLabel18, gridBagConstraints);

        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel6.setLayout(new java.awt.GridBagLayout());

        jLabel19.setText("Dep. Acumulada:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        jPanel6.add(jLabel19, gridBagConstraints);

        tfDepreciacionAcumulada.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 121;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 5, 10);
        jPanel6.add(tfDepreciacionAcumulada, gridBagConstraints);

        tfValorNeto.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 121;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 10, 10);
        jPanel6.add(tfValorNeto, gridBagConstraints);

        jLabel20.setText("Valor Neto:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        jPanel6.add(jLabel20, gridBagConstraints);

        jLabel21.setText("Vida Util:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        jPanel6.add(jLabel21, gridBagConstraints);

        tfVidaUtil.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 30;
        jPanel6.add(tfVidaUtil, gridBagConstraints);

        jLabel22.setText("años");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        jPanel6.add(jLabel22, gridBagConstraints);

        tfDias.setToolTipText("");
        tfDias.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 30;
        jPanel6.add(tfDias, gridBagConstraints);

        jLabel24.setText("dias");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 5);
        jPanel6.add(jLabel24, gridBagConstraints);

        jLabel23.setText("% Depreciación");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 10);
        jPanel6.add(jLabel23, gridBagConstraints);

        tfPorcentajeDepreciacion.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 100;
        jPanel6.add(tfPorcentajeDepreciacion, gridBagConstraints);

        jLabel25.setText("Dep. Gestión");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        jPanel6.add(jLabel25, gridBagConstraints);

        tfDepreciacionGestion.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 100;
        jPanel6.add(tfDepreciacionGestion, gridBagConstraints);

        lMensaje.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lMensaje.setForeground(new java.awt.Color(255, 0, 0));
        lMensaje.setText("Mensaje");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        jPanel6.add(lMensaje, gridBagConstraints);

        jPanel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        bGuardar.setText("Guardar");
        bGuardar.addActionListener(ctrlActivoFijoForm);
        bGuardar.setIcon(IconUI.getResizableIcon("aceptar", 32, 32));

        bExit.setText("Salir");
        bExit.addActionListener(ctrlActivoFijoForm);
        bExit.setIcon(IconUI.getResizableIcon("salir", 32,32));

        bDuplicate.setText("Duplicar");
        bDuplicate.addActionListener(ctrlActivoFijoForm);
        bDuplicate.setIcon(IconUI.getResizableIcon("duplicate", 32, 32));

        bTransfer.setText("Transferir");
        bTransfer.addActionListener(ctrlActivoFijoForm);
        bTransfer.setIcon(IconUI.getResizableIcon("transfer", 32, 32));

        bSearch.setText("Buscar");
        bSearch.addActionListener(ctrlActivoFijoForm);
        bSearch.setIcon(IconUI.getResizableIcon("search", 32, 32));

        bRevaluo.setText("Revaluo");
        bRevaluo.addActionListener(ctrlActivoFijoForm);
        bRevaluo.setIcon(IconUI.getResizableIcon("revaluo", 32, 32));

        bBaja.setText("Dar de baja");
        bBaja.addActionListener(ctrlActivoFijoForm);
        bBaja.setIcon(IconUI.getResizableIcon("baja", 32, 32));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bTransfer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bDuplicate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bExit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bRevaluo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bBaja, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bDuplicate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bTransfer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bRevaluo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bBaja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(bExit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.setLayout(new java.awt.GridBagLayout());

        bApiEstado.setText("Aprobar");
        bApiEstado.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        bApiEstado.addActionListener(ctrlActivoFijoForm);
        jPanel4.add(bApiEstado, new java.awt.GridBagConstraints());

        jPanel8.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel8.setLayout(new java.awt.GridBagLayout());

        jLabel26.setText("Calculados a:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        jPanel8.add(jLabel26, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        jPanel8.add(jLabel27, gridBagConstraints);

        jLabel30.setText("UFV:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        jPanel8.add(jLabel30, gridBagConstraints);

        tfUFVActual.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 10);
        jPanel8.add(tfUFVActual, gridBagConstraints);

        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 1;
        gridBagConstraints.ipady = 46;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel8.add(jSeparator4, gridBagConstraints);

        dccToday.setFormat(0);
        dccToday.addSelectionChangedListener(ctrlActivoFijoForm);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 200;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 10);
        jPanel8.add(dccToday, gridBagConstraints);

        headerActivoFijo.setDescription("");
        headerActivoFijo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/entidad.png"))); // NOI18N
        headerActivoFijo.setIconPosition(org.jdesktop.swingx.JXHeader.IconPosition.LEFT);
        headerActivoFijo.setTitle("Activo Fijo");
        headerActivoFijo.setTitleFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(headerActivoFijo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(headerActivoFijo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void dccIncorporacionOnSelectionChange(datechooser.events.SelectionChangedEvent evt) {//GEN-FIRST:event_dccIncorporacionOnSelectionChange
        Configuracion configuracion = new Configuracion();
        configuracion.setFechaUFV(dccIncorporacion.getSelectedDate().getTime());
        configuracion = (Configuracion) ViewMain.DAO.getObject(configuracion);
        tfIndiveUFV.setText(configuracion.getUFV());
    }//GEN-LAST:event_dccIncorporacionOnSelectionChange
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.jc.swing.CoolButton bApiEstado;
    private org.jc.swing.CoolButton bAuxiliar;
    private org.jc.swing.CoolButton bBaja;
    private org.jc.swing.CoolButton bDuplicate;
    private org.jc.swing.CoolButton bExit;
    private org.jc.swing.CoolButton bFirst;
    private org.jc.swing.CoolButton bGuardar;
    private org.jc.swing.CoolButton bLast;
    private org.jc.swing.CoolButton bNext;
    private org.jc.swing.CoolButton bOficina;
    private org.jc.swing.CoolButton bPrevious;
    private org.jc.swing.CoolButton bResponsable;
    private org.jc.swing.CoolButton bRevaluo;
    private org.jc.swing.CoolButton bSearch;
    private org.jc.swing.CoolButton bTransfer;
    private javax.swing.JCheckBox cbActualizar;
    private javax.swing.JComboBox cbAuxiliar;
    private javax.swing.JCheckBox cbDepreciar;
    private javax.swing.JComboBox cbEstado;
    private javax.swing.JComboBox cbGrupo;
    private javax.swing.JComboBox cbOficina;
    private javax.swing.JComboBox cbResponsable;
    private datechooser.beans.DateChooserCombo dccIncorporacion;
    private datechooser.beans.DateChooserCombo dccToday;
    private org.jdesktop.swingx.JXHeader headerActivoFijo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel lApiEstado;
    private javax.swing.JLabel lMensaje;
    private javax.swing.JLabel lRevaluo;
    private javax.swing.JScrollPane spDescripcion;
    private javax.swing.JScrollPane spObservaciones;
    private javax.swing.JTextArea taDescripcion;
    private javax.swing.JTextArea taObservaciones;
    private javax.swing.JTextField tfCargo;
    private javax.swing.JTextField tfCodigo;
    private javax.swing.JTextField tfCodigoADI;
    private javax.swing.JTextField tfCostoInicial;
    private javax.swing.JTextField tfDepreciacionAcumulada;
    private javax.swing.JTextField tfDepreciacionAcumuladaInicial;
    private javax.swing.JTextField tfDepreciacionGestion;
    private javax.swing.JTextField tfDias;
    private javax.swing.JTextField tfFactorActual;
    private javax.swing.JTextField tfFinanciador;
    private javax.swing.JTextField tfIndiveUFV;
    private javax.swing.JTextField tfNumeroConvenio;
    private javax.swing.JTextField tfPorcentajeDepreciacion;
    private javax.swing.JTextField tfRube;
    private javax.swing.JTextField tfUFVActual;
    private javax.swing.JTextField tfValor;
    private javax.swing.JTextField tfValorNeto;
    private javax.swing.JTextField tfVidaUtil;
    // End of variables declaration//GEN-END:variables

    public void addSearchSimple() {
        commonDialog = new CommonDialog(ViewMain.viewMain, true);
        commonDialog.add(ActivoFijoView.activoFijoView.getSearchForm());
        commonDialog.visibleDialog("Buscar por el Codigo");
    }

    public void addAprobar(boolean enabled, String apiEstado) {
        taDescripcion.setEnabled(enabled);
        cbGrupo.setEnabled(enabled);
        cbAuxiliar.setEnabled(enabled);
        cbOficina.setEnabled(enabled);
        cbResponsable.setEnabled(enabled);
        tfCostoInicial.setEnabled(enabled);
        bAuxiliar.setEnabled(enabled);
        bOficina.setEnabled(enabled);
        bResponsable.setEnabled(enabled);
        lApiEstado.setText(apiEstado);
    }

    @Override
    public Object getObject() {
        activoFijo.setIdActivoFijo(tfCodigo.getText());
        activoFijo.setCodigoADI(tfCodigoADI.getText());
        activoFijo.setIncorporacion(dccIncorporacion.getSelectedDate().getTime());
        activoFijo.setIndiceUFV(tfIndiveUFV.getText());
        activoFijo.setDescripcion(taDescripcion.getText());
        activoFijo.setApiEstado(lApiEstado.getText());
        activoFijo.setEstado(cbEstado.getSelectedIndex());
        activoFijo.setObservaciones(taObservaciones.getText());
        activoFijo.setRube(tfRube.getText());
        activoFijo.setFinanciador(tfFinanciador.getText());
        if (tfNumeroConvenio.getText().equals("")) {
            activoFijo.setNumeroConvenio(0);
        } else {
            activoFijo.setNumeroConvenio(Integer.parseInt(tfNumeroConvenio.getText()));
        }
        activoFijo.setCostoInicial(Double.parseDouble(tfCostoInicial.getText()));
        activoFijo.setDepreciacionAcumuladaInicial(Double.parseDouble(tfDepreciacionAcumuladaInicial.getText()));
        activoFijo.setFactorActual(Double.parseDouble(tfFactorActual.getText()));
        activoFijo.setValor(Double.parseDouble(tfValor.getText()));
        activoFijo.setPorcentajeDepreciacion(Double.parseDouble(tfPorcentajeDepreciacion.getText()));
        activoFijo.setDepreciacionGestion(Double.parseDouble(tfDepreciacionGestion.getText()));
        activoFijo.setDepreciacionAcumulada(Double.parseDouble(tfDepreciacionAcumulada.getText()));
        activoFijo.setValorNeto(Double.parseDouble(tfValorNeto.getText()));
        activoFijo.setDias(Integer.parseInt(tfDias.getText()));
        activoFijo.setVidaUtil(Integer.parseInt(tfVidaUtil.getText()));
        if (cbAuxiliar.getSelectedIndex() != 0 && cbGrupo.getSelectedIndex() != 0) {
            activoFijo.setAuxiliar((Auxiliar) cbAuxiliar.getSelectedItem());
        }
        if (cbResponsable.getSelectedIndex() != 0 && cbOficina.getSelectedIndex() != 0) {
            activoFijo.setResponsable((Responsable) cbResponsable.getSelectedItem());
        }
        activoFijo.setUsuario(ViewMain.viewMain.getUsuario());
        return activoFijo;
    }

    @Override
    public void setObject(Object obj) {
        activoFijo = (ActivoFijo) obj;
        tfCodigo.setText(activoFijo.getIdActivoFijo());
        if (activoFijo.getCodigoADI() == null) {
            tfCodigoADI.setText("");
        } else {
            tfCodigoADI.setText(activoFijo.getCodigoADI());
        }
        if (activoFijo.getIdActivoFijo() == null) {
            tfIndiveUFV.setText(ViewMain.viewMain.getConfiguracion().getUFV());
        } else {
            Configuracion configuracion = new Configuracion();
            configuracion.setFechaUFV(activoFijo.getIncorporacion());
            configuracion = (Configuracion) ViewMain.DAO.getObject(configuracion);
            tfIndiveUFV.setText(configuracion.getUFV());
        }
        Calendar calendarIncorporacion = Calendar.getInstance();
        calendarIncorporacion.setTime(activoFijo.getIncorporacion());
        dccIncorporacion.setSelectedDate(calendarIncorporacion);
        taDescripcion.setText(activoFijo.getDescripcion());
        if (activoFijo.isRevaluo()) {
            lRevaluo.setText("ACTIVO REVALORIZADO");
        } else {
            lRevaluo.setText("");
        }
        if (activoFijo.getValorNeto() == 1) {
            lMensaje.setText("ESTE ACTIVO DE DEBE REVALORIZAR O DAR DE BAJA");
        } else {
            lMensaje.setText("");
        }
        lApiEstado.setText(activoFijo.getApiEstado());
        if (activoFijo.getIdActivoFijo() != null) {
            comboBoxModelGrupo.setSelectedItem(activoFijo.getGrupo());
            comboBoxModelAuxiliar.setSelectedItem(activoFijo.getAuxiliar());
            comboBoxModelOficina.setSelectedItem(activoFijo.getOficina());
            comboBoxModelResponsable.setSelectedItem(activoFijo.getResponsable());
        } else {
            cbGrupo.setSelectedIndex(0);
            cbOficina.setSelectedIndex(0);
        }
        cbEstado.setSelectedIndex(activoFijo.getEstadoIndex());
        if (activoFijo.getObservaciones() == null) {
            taObservaciones.setText("");
        } else {
            taObservaciones.setText(activoFijo.getObservaciones());
        }
        if (activoFijo.getRube() == null) {
            tfRube.setText("");
        } else {
            tfRube.setText(activoFijo.getRube());
        }
        if (activoFijo.getFinanciador() == null) {
            tfFinanciador.setText("");
        } else {
            tfFinanciador.setText(activoFijo.getFinanciador());
        }
        if (activoFijo.getNumeroConvenio() == 0) {
            tfNumeroConvenio.setText("");
        } else {
            tfNumeroConvenio.setText(String.valueOf(activoFijo.getNumeroConvenio()));
        }
        tfCostoInicial.setText(String.valueOf(activoFijo.getCostoInicial()));
        calculo();

    }

    public void calculo() {
        activoFijo.calculo(null);
        tfDepreciacionAcumuladaInicial.setText(String.valueOf(activoFijo.getDepreciacionAcumuladaInicial()));
        tfFactorActual.setText(String.valueOf(activoFijo.getFactorActual()));
        tfValor.setText(String.valueOf(activoFijo.getValor()));
        tfVidaUtil.setText(String.valueOf(activoFijo.getVidaUtil()));
        tfDias.setText(String.valueOf(activoFijo.getDias()));
        tfPorcentajeDepreciacion.setText(String.valueOf(activoFijo.getPorcentajeDepreciacion()));
        tfDepreciacionGestion.setText(String.valueOf(activoFijo.getDepreciacionGestion()));
        tfDepreciacionAcumulada.setText(String.valueOf(activoFijo.getDepreciacionAcumulada()));
        tfValorNeto.setText(String.valueOf(activoFijo.getValorNeto()));
        tfUFVActual.setText(ViewMain.viewMain.getConfiguracion().getUFV());
    }

    public void save() {
        activoFijo = (ActivoFijo) getObject();
        int result = 0;
        if (bGuardar.getText().equals("Guardar")) {
            result = ViewMain.DAO.add(activoFijo);
        } else {
            ViewMain.DAO.update(activoFijo);
        }
        if (result == 1) {
            setObject(activoFijo);
            bGuardar.setText("Actualizar");
        }
        ActivoFijoView.activoFijoView.getActivoFijoTable().reload();
    }

    private class CtrlActivoFijoForm implements ActionListener, FocusListener, ItemListener, SelectionChangedListener {

        @Override
        public void actionPerformed(ActionEvent e) {
            Object aux = e.getSource();
            if (aux.equals(bGuardar)) {

                if (cbAuxiliar.getSelectedIndex() != 0 && cbGrupo.getSelectedIndex() != 0) {
                    if (cbResponsable.getSelectedIndex() != 0 && cbOficina.getSelectedIndex() != 0) {
                        save();
                    } else {
                        JOptionPane.showMessageDialog(ViewMain.viewMain, "Tiene que seleccionar un Responsable", "Mensaje", JOptionPane.ERROR_MESSAGE);
                    }
                } else {
                    JOptionPane.showMessageDialog(ViewMain.viewMain, "Tiene que seleccionar un Auxiliar", "Mensaje", JOptionPane.ERROR_MESSAGE);
                }
            } else if (aux.equals(bDuplicate)) {
                ActivoFijoView.activoFijoView.addDuplicate(activoFijo);
            } else if (aux.equals(bTransfer)) {
                ActivoFijoView.activoFijoView.addTranfer(activoFijo);
            } else if (aux.equals(bRevaluo)) {
                ActivoFijoView.activoFijoView.getRevaluoForm().getbView().setVisible(true);
                ActivoFijoView.activoFijoView.getRevaluoForm().getbGuardar().setVisible(true);
                ActivoFijoView.activoFijoView.getRevaluoForm().initConfiguracion(true);
                ActivoFijoView.activoFijoView.addRevaluo(activoFijo, new Revaluo());
            } else if (aux.equals(bBaja)) {
                ActivoFijoView.activoFijoView.getBajaForm().getbView().setVisible(true);
                ActivoFijoView.activoFijoView.getBajaForm().getbGuardar().setVisible(true);
                ActivoFijoView.activoFijoView.getBajaForm().initConfiguracion(true);
                Baja baja = new Baja();
                baja.setActivoFijo(activoFijo);
                ActivoFijoView.activoFijoView.addBaja(baja);
            } else if (aux.equals(bSearch)) {
                addSearchSimple();
            } else if (aux.equals(bExit)) {
                ActivoFijoView.activoFijoView.getCommonDialog().dispose();
            } else if (aux.equals(bApiEstado)) {
                if (activoFijo.getApiEstado().equals("ELABORADO")) {
                    activoFijo.setApiEstado("APROBADO");
                    bApiEstado.setText("Elaborar");
                    addAprobar(false, activoFijo.getApiEstado());
                } else {
                    activoFijo.setApiEstado("ELABORADO");
                    bApiEstado.setText("Aprobar");
                    addAprobar(true, activoFijo.getApiEstado());
                }
                activoFijo.setUsuario(ViewMain.viewMain.getUsuario());
                ViewMain.DAO.update(activoFijo);
                ActivoFijoView.activoFijoView.getActivoFijoTable().reload();
            } else if (aux.equals(bAuxiliar)) {
                AuxiliarView.auxiliarView.addNew();
                Grupo grupo = (Grupo) cbGrupo.getSelectedItem();
                Auxiliar auxiliar = new Auxiliar();
                auxiliar.setGrupo(grupo);
                List list = ViewMain.DAO.getObjects(auxiliar);
                cbAuxiliar.setEnabled(true);
                comboBoxModelAuxiliar = new DefaultComboBoxModel();
                comboBoxModelAuxiliar.removeAllElements();
                for (Object o : list) {
                    comboBoxModelAuxiliar.addElement((Auxiliar) o);
                }
                cbAuxiliar.setModel(comboBoxModelAuxiliar);
                cbAuxiliar.updateUI();
            } else if (aux.equals(bOficina)) {
                OficinaView.oficinaView.addNew();
                Oficina oficina = new Oficina();
                oficina.setUnidad(ViewMain.viewMain.getUnidad());
                initComboBoxOficina(ViewMain.DAO.getObjects(oficina));
            } else if (aux.equals(bResponsable)) {
                ResponsableView.responsableView.addNew();
                Oficina oficina = (Oficina) cbOficina.getSelectedItem();
                Responsable responsable = new Responsable();
                responsable.setOficina(oficina);
                List list = ViewMain.DAO.getObjects(responsable);
                cbResponsable.setEnabled(true);
                comboBoxModelResponsable = new DefaultComboBoxModel();
                comboBoxModelResponsable.removeAllElements();
                for (Object o : list) {
                    comboBoxModelResponsable.addElement((Responsable) o);
                }
                cbResponsable.setModel(comboBoxModelResponsable);
                tfCargo.setText("");
            }
        }

        @Override
        public void focusGained(FocusEvent e) {
            Object aux = e.getSource();
            if (aux.equals(tfCodigoADI)) {
                tfCodigoADI.selectAll();
            } else if (aux.equals(taDescripcion)) {
                taDescripcion.selectAll();
            } else if (aux.equals(taObservaciones)) {
                taObservaciones.selectAll();
            } else if (aux.equals(tfRube)) {
                tfRube.selectAll();
            } else if (aux.equals(tfFinanciador)) {
                tfFinanciador.selectAll();
            } else if (aux.equals(tfNumeroConvenio)) {
                tfNumeroConvenio.selectAll();
            } else if (aux.equals(tfCostoInicial)) {
                tfCostoInicial.selectAll();
            }
        }

        @Override
        public void focusLost(FocusEvent e) {
            activoFijo.setCostoInicial(Double.parseDouble(tfCostoInicial.getText()));
            calculo();
        }

        @Override
        public void itemStateChanged(ItemEvent e) {
            Object aux = e.getSource();
            if (aux.equals(cbGrupo)) {
                Object object = cbGrupo.getSelectedItem();
                if (object instanceof Grupo) {
                    Grupo grupo = (Grupo) object;
                    cbDepreciar.setSelected(grupo.isDepreciar());
                    cbActualizar.setSelected(grupo.isActualizar());
                    if (!activoFijo.isRevaluo()) {
                        activoFijo.setVidaUtil(grupo.getVidaUtil());
                    }
                    if (activoFijo.isRevaluo()) {
                        tfVidaUtil.setText(String.valueOf(activoFijo.getVidaUtil()));
                    } else {
                        tfVidaUtil.setText(String.valueOf(activoFijo.getVidaUtil()));
                    }
                    Auxiliar auxiliar = new Auxiliar();
                    auxiliar.setGrupo(grupo);
                    auxiliar.setUnidad(ViewMain.viewMain.getUnidad());
                    List list = ViewMain.DAO.getObjects(auxiliar);
                    if (!list.isEmpty()) {
                        cbAuxiliar.setEnabled(true);
                        comboBoxModelAuxiliar = new DefaultComboBoxModel();
                        comboBoxModelAuxiliar.removeAllElements();
                        comboBoxModelAuxiliar.addElement("Seleccione Auxliar");
                        for (Object o : list) {
                            comboBoxModelAuxiliar.addElement((Auxiliar) o);
                        }
                        cbAuxiliar.setModel(comboBoxModelAuxiliar);
                    } else {
                        cbAuxiliar.setEnabled(false);
                        comboBoxModelAuxiliar.removeAllElements();
                        cbAuxiliar.setModel(comboBoxModelAuxiliar);
                    }
                }
            } else if (aux.equals(cbOficina)) {
                Object object = cbOficina.getSelectedItem();
                if (object instanceof Oficina) {
                    Oficina oficina = (Oficina) object;
                    Responsable responsable = new Responsable();
                    responsable.setOficina(oficina);
                    List list = ViewMain.DAO.getObjects(responsable);
                    if (!list.isEmpty()) {
                        cbResponsable.setEnabled(true);
                        comboBoxModelResponsable = new DefaultComboBoxModel();
                        comboBoxModelResponsable.removeAllElements();
                        comboBoxModelResponsable.addElement("Seleccione Responsable");
                        for (Object o : list) {
                            comboBoxModelResponsable.addElement((Responsable) o);
                        }
                        cbResponsable.setModel(comboBoxModelResponsable);
                    } else {
                        cbResponsable.setEnabled(false);
                        comboBoxModelResponsable.removeAllElements();
                        cbResponsable.setModel(comboBoxModelResponsable);
                    }
                }
                tfCargo.setText("");
            } else if (aux.equals(cbResponsable)) {
                Responsable responsable = (Responsable) cbResponsable.getSelectedItem();
                if (responsable != null) {
                    tfCargo.setText(responsable.getCargo());
                }
            }
        }

        @Override
        public void onSelectionChange(SelectionChangedEvent sce) {
            activoFijo.calculo(dccToday.getSelectedDate().getTime());
            tfDepreciacionAcumuladaInicial.setText(String.valueOf(activoFijo.getDepreciacionAcumuladaInicial()));
            tfFactorActual.setText(String.valueOf(activoFijo.getFactorActual()));
            tfValor.setText(String.valueOf(activoFijo.getValor()));
            tfVidaUtil.setText(String.valueOf(activoFijo.getVidaUtil()));
            tfDias.setText(String.valueOf(activoFijo.getDias()));
            tfPorcentajeDepreciacion.setText(String.valueOf(activoFijo.getPorcentajeDepreciacion()));
            tfDepreciacionGestion.setText(String.valueOf(activoFijo.getDepreciacionGestion()));
            tfDepreciacionAcumulada.setText(String.valueOf(activoFijo.getDepreciacionAcumulada()));
            tfValorNeto.setText(String.valueOf(activoFijo.getValorNeto()));
            Configuracion configuracion = new Configuracion();
            configuracion.setFechaUFV(dccToday.getSelectedDate().getTime());
            configuracion = (Configuracion) ViewMain.DAO.getObject(configuracion);
            tfUFVActual.setText(configuracion.getUFV());
        }
    }
}
