/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view.activos;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import java.util.Calendar;
import javax.swing.JOptionPane;
import model.domain.ActivoFijo;
import model.domain.Baja;
import org.jc.swing.CoolButton;
import utils.IconUI;
import view.ViewMain;

/**
 * BajaForm
 *
 * @author Sergio Antonio Ochoa Martinez - gnu.java.sergio@gmail.com
 */
public class BajaForm extends javax.swing.JPanel {

    private CtrlBajaForm ctrlBajaForm;
    private ActivoFijo activoFijo;
    private Baja baja;

    /**
     * BajaForm
     */
    public BajaForm() {
        ctrlBajaForm = new CtrlBajaForm();
        initComponents();
    }

    void initConfiguracion(boolean valor) {
        tfDisposicionRespaldo.setEditable(valor);
        listMotivoBaja.setEnabled(valor);
        taMotivo.setEditable(valor);
    }

    public CoolButton getbView() {
        return bView;
    }

    public CoolButton getbCancelar() {
        return bCancelar;
    }

    public CoolButton getbGuardar() {
        return bGuardar;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        headerBaja = new org.jdesktop.swingx.JXHeader();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tfIdActivoFijo = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        taDescripcion = new javax.swing.JTextArea();
        tfDisposicionRespaldo = new javax.swing.JTextField();
        tfIndiceUFV = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        bGuardar = new org.jc.swing.CoolButton(0);
        bCancelar = new org.jc.swing.CoolButton(0);
        jPanel7 = new javax.swing.JPanel();
        bView = new org.jc.swing.CoolButton(0);
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        taMotivo = new javax.swing.JTextArea();
        jLabel14 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        listMotivoBaja = new javax.swing.JList();
        jPanel4 = new javax.swing.JPanel();
        tfValor = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tfVidaUtil = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tfPorcentajeDepreciacion = new javax.swing.JTextField();
        tfDepreciacionGestion = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        tfDias = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        tfDepreciacionAcumulada = new javax.swing.JTextField();
        tfCostoInicial = new javax.swing.JTextField();
        tfFactorAnterior = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        tfValorNeto = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        dccIncorporacion = new datechooser.beans.DateChooserCombo();
        dccFechaBaja = new datechooser.beans.DateChooserCombo();

        headerBaja.setDescription("");
        headerBaja.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/entidad.png"))); // NOI18N
        headerBaja.setIconPosition(org.jdesktop.swingx.JXHeader.IconPosition.LEFT);
        headerBaja.setTitle("Dar Baja Activo Fijo");
        headerBaja.setTitleFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("Codigo:");

        tfIdActivoFijo.setEditable(false);

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        taDescripcion.setEditable(false);
        taDescripcion.setColumns(20);
        taDescripcion.setRows(5);
        taDescripcion.setLineWrap(true);
        taDescripcion.setWrapStyleWord(true);
        jScrollPane1.setViewportView(taDescripcion);

        tfDisposicionRespaldo.addFocusListener(ctrlBajaForm);

        tfIndiceUFV.setEditable(false);

        jLabel8.setText("Indice UFV:");

        jLabel10.setText("Disposicion de Respaldo:");

        jLabel11.setText("Descripción:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel1)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfIndiceUFV, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                    .addComponent(tfIdActivoFijo)
                    .addComponent(tfDisposicionRespaldo))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfIdActivoFijo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfIndiceUFV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfDisposicionRespaldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))))
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setLayout(new java.awt.BorderLayout());

        bGuardar.setText("Guardar");
        bGuardar.addActionListener(ctrlBajaForm);
        bGuardar.setIcon(IconUI.getResizableIcon("aceptar", 32, 32));
        jPanel6.add(bGuardar);

        bCancelar.setText("Cancelar");
        bCancelar.addActionListener(ctrlBajaForm);
        bCancelar.setIcon(IconUI.getResizableIcon("cancelar", 32, 32));
        jPanel6.add(bCancelar);

        jPanel3.add(jPanel6, java.awt.BorderLayout.LINE_END);

        bView.setText("Ver Bajas");
        bView.addActionListener(ctrlBajaForm);
        bView.setIcon(IconUI.getResizableIcon("view", 32, 32));
        jPanel7.add(bView);

        jPanel3.add(jPanel7, java.awt.BorderLayout.WEST);

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        taMotivo.setColumns(20);
        taMotivo.setRows(5);
        taMotivo.setLineWrap(true);
        taMotivo.setWrapStyleWord(true);
        taMotivo.addFocusListener(ctrlBajaForm);
        jScrollPane2.setViewportView(taMotivo);

        jLabel14.setText("Observaciones o Motivos");

        jLabel19.setText("Motivo de la Baja");

        listMotivoBaja.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Disposición definitiva de bienes", "Hurto, robo o perdida fortuita", "Mermas", "Vencimiento, descomposiciones, alteraciones y Inutilizacion", "Obsolescencia", "Desmantelamiento total o parcial de edificaciones", "Siniestros", "ERROR DE TRANSCRIPCION" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        listMotivoBaja.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listMotivoBaja.setRequestFocusEnabled(false);
        listMotivoBaja.setSelectedIndex(0);
        jScrollPane3.setViewportView(listMotivoBaja);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel4.setLayout(new java.awt.GridBagLayout());

        tfValor.setEditable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 74;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(3, 0, 6, 0);
        jPanel4.add(tfValor, gridBagConstraints);

        jLabel2.setText("Vida Util:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 0, 10);
        jPanel4.add(jLabel2, gridBagConstraints);

        jLabel3.setText("Valor:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 10);
        jPanel4.add(jLabel3, gridBagConstraints);

        tfVidaUtil.setEditable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 74;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 0, 3, 0);
        jPanel4.add(tfVidaUtil, gridBagConstraints);

        jLabel6.setText("% Depreciacion:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 0, 10);
        jPanel4.add(jLabel6, gridBagConstraints);

        jLabel7.setText("Dep. Gestión:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 10);
        jPanel4.add(jLabel7, gridBagConstraints);

        tfPorcentajeDepreciacion.setEditable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 44;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel4.add(tfPorcentajeDepreciacion, gridBagConstraints);

        tfDepreciacionGestion.setEditable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 44;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel4.add(tfDepreciacionGestion, gridBagConstraints);

        jLabel9.setText("Dias Cosumidos:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 10);
        jPanel4.add(jLabel9, gridBagConstraints);

        tfDias.setEditable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 54;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel4.add(tfDias, gridBagConstraints);

        jLabel15.setText("Dep. Acumulada:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 0, 10);
        jPanel4.add(jLabel15, gridBagConstraints);

        tfDepreciacionAcumulada.setEditable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 54;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel4.add(tfDepreciacionAcumulada, gridBagConstraints);

        tfCostoInicial.setEditable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 54;
        jPanel4.add(tfCostoInicial, gridBagConstraints);

        tfFactorAnterior.setEditable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 54;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel4.add(tfFactorAnterior, gridBagConstraints);

        jLabel16.setText("Factor Anterior:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 0, 10);
        jPanel4.add(jLabel16, gridBagConstraints);

        jLabel17.setText("Valor Neto:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 10);
        jPanel4.add(jLabel17, gridBagConstraints);

        jLabel18.setText("Costo Inicial");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 0, 20);
        jPanel4.add(jLabel18, gridBagConstraints);

        tfValorNeto.setEditable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 54;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel4.add(tfValorNeto, gridBagConstraints);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel4.setText("Fecha de Incorporación:");

        jLabel5.setText("Fecha de Baja:");

        dccIncorporacion.setFormat(0);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(dccIncorporacion, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dccFechaBaja, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dccIncorporacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dccFechaBaja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(headerBaja, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 762, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(headerBaja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.jc.swing.CoolButton bCancelar;
    private org.jc.swing.CoolButton bGuardar;
    private org.jc.swing.CoolButton bView;
    private datechooser.beans.DateChooserCombo dccFechaBaja;
    private datechooser.beans.DateChooserCombo dccIncorporacion;
    private org.jdesktop.swingx.JXHeader headerBaja;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JList listMotivoBaja;
    private javax.swing.JTextArea taDescripcion;
    private javax.swing.JTextArea taMotivo;
    private javax.swing.JTextField tfCostoInicial;
    private javax.swing.JTextField tfDepreciacionAcumulada;
    private javax.swing.JTextField tfDepreciacionGestion;
    private javax.swing.JTextField tfDias;
    private javax.swing.JTextField tfDisposicionRespaldo;
    private javax.swing.JTextField tfFactorAnterior;
    private javax.swing.JTextField tfIdActivoFijo;
    private javax.swing.JTextField tfIndiceUFV;
    private javax.swing.JTextField tfPorcentajeDepreciacion;
    private javax.swing.JTextField tfValor;
    private javax.swing.JTextField tfValorNeto;
    private javax.swing.JTextField tfVidaUtil;
    // End of variables declaration//GEN-END:variables

    public void setObject(Object obj) {
        this.baja = (Baja) obj;
        if(baja.getActivoFijo().getApiEstado().equals("ELABORADO")){
              bGuardar.setEnabled(false);
        }
        Calendar calendarIncorporacion = Calendar.getInstance();
        calendarIncorporacion.setTime(baja.getActivoFijo().getIncorporacion());
        dccIncorporacion.setSelectedDate(calendarIncorporacion);
        Calendar calendarFechaBaja = Calendar.getInstance();
        calendarFechaBaja.setTime(baja.getFechaBaja());
        dccFechaBaja.setSelectedDate(calendarFechaBaja);
        tfIdActivoFijo.setText(baja.getActivoFijo().getIdActivoFijo());
        taDescripcion.setText(baja.getActivoFijo().getDescripcion());
        tfIndiceUFV.setText(baja.getActivoFijo().getIndiceUFV());
        tfDisposicionRespaldo.setText(baja.getDisposicionRespaldo());
        tfVidaUtil.setText(String.valueOf(baja.getActivoFijo().getVidaUtil()));
        tfValor.setText(String.valueOf(baja.getActivoFijo().getValor()));
        tfPorcentajeDepreciacion.setText(String.valueOf(baja.getActivoFijo().getPorcentajeDepreciacion()));
        tfDepreciacionGestion.setText(String.valueOf(baja.getActivoFijo().getDepreciacionGestion()));
        tfDias.setText(String.valueOf(baja.getActivoFijo().getDias()));
        tfDepreciacionAcumulada.setText(String.valueOf(baja.getActivoFijo().getDepreciacionAcumulada()));
        tfValorNeto.setText(String.valueOf(baja.getActivoFijo().getValorNeto()));
        tfCostoInicial.setText(String.valueOf(baja.getActivoFijo().getCostoInicial()));
        if (baja.getIdBaja() == 0) {
            listMotivoBaja.setSelectedIndex(0);
        } else {
            listMotivoBaja.setSelectedValue(baja.getMotivoBaja(), true);
        }

        taMotivo.setText(baja.getMotivo());
    }

    public void getObject() {
        baja.setFechaBaja(dccFechaBaja.getSelectedDate().getTime());
        baja.setDisposicionRespaldo(tfDisposicionRespaldo.getText());
        baja.setMotivoBaja(listMotivoBaja.getSelectedValue().toString());
        baja.setMotivo(taMotivo.getText());
        baja.setUnidad(ViewMain.viewMain.getUnidad());
        baja.setUsuario(ViewMain.viewMain.getUsuario());
        baja.getActivoFijo().setUsuario(ViewMain.viewMain.getUsuario());
        int option = JOptionPane.showConfirmDialog(ViewMain.viewMain, "Esta seguro de que quiere dar de baja este Activo?", "Mensaje", JOptionPane.YES_NO_OPTION);
        if (option == JOptionPane.YES_OPTION) {
            ViewMain.DAO.add(baja);
            baja.getActivoFijo().setBaja(true);
            ViewMain.DAO.update(baja.getActivoFijo());
            ActivoFijoView.activoFijoView.getActivoFijoTable().reload();
            ActivoFijoView.activoFijoView.getDialog().dispose();
            ActivoFijoView.activoFijoView.getCommonDialog().dispose();
        }
    }

    private class CtrlBajaForm implements ActionListener, FocusListener {

        @Override
        public void actionPerformed(ActionEvent e) {
            Object aux = e.getSource();
            if (aux.equals(bGuardar)) {
                getObject();
            } else if (aux.equals(bCancelar)) {
                ActivoFijoView.activoFijoView.getDialog().dispose();
            } else if (aux.equals(bView)) {
                BajaView.bajaView.getBajaTable().reload();
                ActivoFijoView.activoFijoView.getDialog().dispose();
                ActivoFijoView.activoFijoView.getCommonDialog().dispose();
                ViewMain.viewMain.getFrontend().hide(ViewMain.viewMain.getDockableBaja());
                ViewMain.viewMain.getFrontend().show(ViewMain.viewMain.getDockableBaja());
            }
        }

        @Override
        public void focusGained(FocusEvent e) {
            Object aux = e.getSource();
            if (aux.equals(tfDisposicionRespaldo)) {
                tfDisposicionRespaldo.selectAll();
            } else if (aux.equals(taMotivo)) {
                taMotivo.selectAll();
            }
        }

        @Override
        public void focusLost(FocusEvent e) {
        }
    }
}