/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view.activos;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import model.domain.ActivoFijo;
import utils.IconUI;
import view.ViewMain;

/**
 * DuplicateForm
 *
 * @author Sergio Antonio Ochoa Martinez - gnu.java.sergio@gmail.com
 * @version 0.1
 */
public class DuplicateForm extends javax.swing.JPanel {

    private CtrlDuplicateForm ctrlDuplicateForm;
    private ActivoFijo activoFijo;

    /**
     * DuplicateForm
     */
    public DuplicateForm() {
        ctrlDuplicateForm = new CtrlDuplicateForm();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelCurves1 = new org.jc.swing.panel.PanelCurves();
        jPanel1 = new javax.swing.JPanel();
        bAceptar = new org.jc.swing.CoolButton(0);
        bCancel = new org.jc.swing.CoolButton(0);
        jPanel2 = new javax.swing.JPanel();
        tfIdActivoFijo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        tfCantidad = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        headerActivoFijo = new org.jdesktop.swingx.JXHeader();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 10, 10));

        bAceptar.setText("Aceptar");
        bAceptar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bAceptar.addActionListener(ctrlDuplicateForm);
        bAceptar.setIcon(IconUI.getResizableIcon("aceptar", 32, 32));
        bAceptar.addKeyListener(ctrlDuplicateForm);
        jPanel1.add(bAceptar);

        bCancel.setText("Cancelar");
        bCancel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bCancel.addActionListener(ctrlDuplicateForm);
        bCancel.addKeyListener(ctrlDuplicateForm);
        bCancel.setIcon(IconUI.getResizableIcon("cancelar", 32, 32));
        jPanel1.add(bCancel);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tfIdActivoFijo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tfIdActivoFijo.addKeyListener(ctrlDuplicateForm);
        tfIdActivoFijo.addFocusListener(ctrlDuplicateForm);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Codigo Nuevo:");

        tfCantidad.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tfCantidad.addFocusListener(ctrlDuplicateForm);
        tfCantidad.addKeyListener(ctrlDuplicateForm);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Cantidad:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfCantidad, javax.swing.GroupLayout.DEFAULT_SIZE, 336, Short.MAX_VALUE)
                    .addComponent(tfIdActivoFijo))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfIdActivoFijo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelCurves1Layout = new javax.swing.GroupLayout(panelCurves1);
        panelCurves1.setLayout(panelCurves1Layout);
        panelCurves1Layout.setHorizontalGroup(
            panelCurves1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCurves1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCurves1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelCurves1Layout.setVerticalGroup(
            panelCurves1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCurves1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(69, Short.MAX_VALUE))
        );

        add(panelCurves1, java.awt.BorderLayout.CENTER);

        headerActivoFijo.setDescription("");
        headerActivoFijo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/entidad.png"))); // NOI18N
        headerActivoFijo.setIconPosition(org.jdesktop.swingx.JXHeader.IconPosition.LEFT);
        headerActivoFijo.setTitle("Duplicar");
        headerActivoFijo.setTitleFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        add(headerActivoFijo, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.jc.swing.CoolButton bAceptar;
    private org.jc.swing.CoolButton bCancel;
    private org.jdesktop.swingx.JXHeader headerActivoFijo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private org.jc.swing.panel.PanelCurves panelCurves1;
    private javax.swing.JTextField tfCantidad;
    private javax.swing.JTextField tfIdActivoFijo;
    // End of variables declaration//GEN-END:variables

    public void setObject(Object obj) {
        activoFijo = (ActivoFijo) obj;
        tfIdActivoFijo.setText(activoFijo.getIdActivoFijo());
        tfCantidad.setText("0");
    }

    public void getObject() {
        String codigo = tfIdActivoFijo.getText();
        int cantidad = Integer.parseInt(tfCantidad.getText());
        if (cantidad == 0) {
            cantidad++;
        }
        int i = 0;
        activoFijo.setUsuario(ViewMain.viewMain.getUsuario());
        int codigoLimit = codigo.length();
        int id = 0;
        do {
            id = Integer.parseInt(codigo.substring(9, codigoLimit));
            activoFijo.setIdActivoFijo(codigo);
            if (activoFijo.getVidaUtil() == 0) {
                activoFijo.setVidaUtil(activoFijo.getGrupo().getVidaUtil());
            } else {
            }
            int insert = ViewMain.DAO.add(activoFijo);
            id++;
            int idCantidad = String.valueOf(id).length();
            char[] idChar = String.valueOf(id).toCharArray();
            char[] codigoChar = codigo.toCharArray();
            for (int j = 1; j <= idCantidad; j++) {
                codigoChar[codigoLimit - j] = idChar[idCantidad - j];
            }
            codigo = "";
            for (int j = 0; j < codigoLimit; j++) {
                codigo += codigoChar[j];
            }
            if (insert == 1) {
                i++;
            }
        } while (i < cantidad);
        ActivoFijoForm.activoFijoForm.setObject(activoFijo);
        ActivoFijoView.activoFijoView.getActivoFijoTable().reload();
        ActivoFijoView.activoFijoView.getDialog().dispose();
    }

    private class CtrlDuplicateForm extends KeyAdapter implements ActionListener, FocusListener {

        @Override
        public void actionPerformed(ActionEvent e) {
            Object aux = e.getSource();
            if (aux.equals(bAceptar)) {
                getObject();
            } else if (aux.equals(bCancel)) {
                ActivoFijoView.activoFijoView.getDialog().dispose();
            }
        }

        @Override
        public void keyPressed(KeyEvent e) {
            if (e.getKeyCode() == 10) {
                if (tfIdActivoFijo.isFocusable()) {
                    getObject();
                } else if (tfCantidad.isFocusable()) {
                    getObject();
                } else if (bAceptar.isFocusable()) {
                    getObject();
                } else if (bCancel.isFocusable()) {
                    ActivoFijoView.activoFijoView.getDialog().dispose();
                }
            }
        }

        @Override
        public void focusGained(FocusEvent e) {
            Object aux = e.getSource();
            if (aux.equals(tfIdActivoFijo)) {
                tfIdActivoFijo.selectAll();
            } else if (aux.equals(tfCantidad)) {
                tfCantidad.selectAll();
            }
        }

        @Override
        public void focusLost(FocusEvent e) {
        }
    }
}
