/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view.activos;

import java.awt.BorderLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import model.domain.Revaluo;
import utils.IconUI;
import view.ViewMain;
import view.common.CommonDialog;

/**
 * RevaluoView
 *
 * @author Sergio Antonio Ochoa Martinez - gnu.java.sergio@gmail.com
 */
public class RevaluoView extends javax.swing.JPanel {

    private RevaluoView.CtrlRevaluoView ctrlRevaluoView;
    private RevaluoTable revaluoTable;
    public static RevaluoView revaluoView;
    private CommonDialog commonDialog;
    private Revaluo revaluo = new Revaluo();
    
    public RevaluoView() {
        revaluoView = this;
        ctrlRevaluoView = new CtrlRevaluoView();
        initComponents();
        revaluoTable = new RevaluoTable();
        this.add(revaluoTable, BorderLayout.CENTER);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        bDetail = new org.jc.swing.CoolButton(1);
        bExit = new org.jc.swing.CoolButton(2);

        setLayout(new java.awt.BorderLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 0, 5));

        bDetail.setText("Detalle");
        bDetail.setIcon(IconUI.getResizableIcon("view", 32,32));
        bDetail.addActionListener(ctrlRevaluoView);
        jPanel1.add(bDetail);

        bExit.setText("Salir");
        bExit.setIcon(IconUI.getResizableIcon("salir", 32,32));
        bExit.addActionListener(ctrlRevaluoView);
        jPanel1.add(bExit);

        add(jPanel1, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.jc.swing.CoolButton bDetail;
    private org.jc.swing.CoolButton bExit;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    public CommonDialog getCommonDialog() {
        return commonDialog;
    }

    public RevaluoTable getRevaluoTable() {
        return revaluoTable;
    }

    public Revaluo getRevaluo() {
        return revaluo;
    }

    public void setRevaluo(Revaluo revaluo) {
        this.revaluo = revaluo;
    }


    public void addDetail() {                
        revaluo = new Revaluo();
        revaluo = (Revaluo) revaluoTable.getSelectedObject(revaluo);
        if (revaluo != null) {
            revaluo = (Revaluo) ViewMain.DAO.getObject(revaluo);            
            ActivoFijoView.activoFijoView.getRevaluoForm().getbView().setVisible(false);
            ActivoFijoView.activoFijoView.getRevaluoForm().getbGuardar().setVisible(false);            
            ActivoFijoView.activoFijoView.getRevaluoForm().initConfiguracion(false);
            ActivoFijoView.activoFijoView.addRevaluo(null,revaluo);
        } else {
            JOptionPane.showMessageDialog(ViewMain.viewMain, "No selecciono ninguna Baja", "Mensaje", JOptionPane.ERROR_MESSAGE);            
        }
    }

    private class CtrlRevaluoView implements ActionListener {

        @Override
        public void actionPerformed(ActionEvent e) {
            Object aux = e.getSource();
            if (aux.equals(bDetail)) {
                addDetail();
            } else if(aux.equals(bExit)){
                ViewMain.viewMain.getFrontend().hide(ViewMain.viewMain.getDockableRevaluo());                
            }
        }
    }
}
