/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view.activos;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import java.util.Calendar;
import javax.swing.JOptionPane;
import model.domain.ActivoFijo;
import model.domain.Revaluo;
import org.jc.JCCalendar;
import org.jc.swing.CoolButton;
import utils.IconUI;
import view.ViewMain;

/**
 * RevaluoForm
 *
 * @author Sergio Antonio Ochoa Martinez - gnu.java.sergio@gmail.com
 * @version 0.1
 */
public final class RevaluoForm extends javax.swing.JPanel {

    private CtrlRevaluoForm ctrlRevaluoForm;
    private ActivoFijo activoFijo;
    private Revaluo revaluo;

    /**
     * Creates new form RevaluoForm
     */
    public RevaluoForm() {
        ctrlRevaluoForm = new CtrlRevaluoForm();
        initComponents();
        initConfiguracion(true);
    }

    public void initConfiguracion(boolean valor) {
        dccIncorporacion.setEnabled(valor);
        dccFechaRevaluoTecnico.setEnabled(valor);
        taDescripcion.setEditable(valor);
        tfCostoInicialNuevo.setEditable(valor);
        tfVidaUtilNuevo.setEditable(valor);
        tfDisposicionRespaldo.setEditable(valor);
        taMotivo.setEditable(valor);
    }

    public CoolButton getbView() {
        return bView;
    }

    public CoolButton getbCancelar() {
        return bCancelar;
    }

    public CoolButton getbGuardar() {
        return bGuardar;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tfIdActivoFijo = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        bGuardar = new org.jc.swing.CoolButton(0);
        bCancelar = new org.jc.swing.CoolButton(0);
        jPanel7 = new javax.swing.JPanel();
        bView = new org.jc.swing.CoolButton(0);
        headerRevaluo = new org.jdesktop.swingx.JXHeader();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        dccIncorporacion = new datechooser.beans.DateChooserCombo();
        dccFechaRevaluoTecnico = new datechooser.beans.DateChooserCombo();
        jPanel4 = new javax.swing.JPanel();
        tfCostoInicialNuevo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tfCostoInicial = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tfVidaUtil = new javax.swing.JTextField();
        tfVidaUtilNuevo = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        tfIndiceUFV = new javax.swing.JTextField();
        tfIndiveUFVNuevo = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        tfDisposicionRespaldo = new javax.swing.JTextField();
        tfDepreciacionGestion = new javax.swing.JTextField();
        tfDespreciacionAcumulada = new javax.swing.JTextField();
        tfValorNeto = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        taMotivo = new javax.swing.JTextArea();
        jLabel14 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        lRevaluo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taDescripcion = new javax.swing.JTextArea();

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("Codigo:");

        tfIdActivoFijo.setEditable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfIdActivoFijo, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfIdActivoFijo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(35, 35, 35))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setLayout(new java.awt.BorderLayout());

        bGuardar.setText("Guardar");
        bGuardar.addActionListener(ctrlRevaluoForm);
        bGuardar.setIcon(IconUI.getResizableIcon("aceptar", 32, 32));
        jPanel6.add(bGuardar);

        bCancelar.setText("Cancelar");
        bCancelar.addActionListener(ctrlRevaluoForm);
        bCancelar.setIcon(IconUI.getResizableIcon("cancelar", 32, 32));
        jPanel6.add(bCancelar);

        jPanel3.add(jPanel6, java.awt.BorderLayout.LINE_END);

        bView.setText("Ver Anteriores");
        bView.addActionListener(ctrlRevaluoForm);
        bView.setIcon(IconUI.getResizableIcon("view", 32, 32));
        jPanel7.add(bView);

        jPanel3.add(jPanel7, java.awt.BorderLayout.WEST);

        headerRevaluo.setDescription("");
        headerRevaluo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/entidad.png"))); // NOI18N
        headerRevaluo.setIconPosition(org.jdesktop.swingx.JXHeader.IconPosition.LEFT);
        headerRevaluo.setTitle("Revaluo");
        headerRevaluo.setTitleFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel4.setText("Fecha Incorporación:");

        jLabel5.setText("Fecha Revaluo Tecnico:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(dccIncorporacion, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(dccFechaRevaluoTecnico, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dccIncorporacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dccFechaRevaluoTecnico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tfCostoInicialNuevo.addFocusListener(ctrlRevaluoForm);

        jLabel2.setText("Viejo Costo:");

        jLabel3.setText("Nuevo Costo:");

        tfCostoInicial.setEditable(false);

        jLabel6.setText("Años de vida:");

        jLabel7.setText("Nuevos años de vida:");

        tfVidaUtil.setEditable(false);

        tfVidaUtilNuevo.addFocusListener(ctrlRevaluoForm);

        jLabel8.setText("Indice UFV Anterior:");

        jLabel9.setText("Indice UFV Actual:");

        tfIndiceUFV.setEditable(false);

        tfIndiveUFVNuevo.setEditable(false);

        jLabel10.setText("Disposicion de Respaldo:");

        jLabel11.setText("Depreciación Gestión:");

        jLabel12.setText("Depreciación Acumulada:");

        jLabel13.setText("Valor Neto:");

        tfDisposicionRespaldo.addFocusListener(ctrlRevaluoForm);

        tfDepreciacionGestion.setEditable(false);

        tfDespreciacionAcumulada.setEditable(false);

        tfValorNeto.setEditable(false);

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        taMotivo.setColumns(20);
        taMotivo.setRows(5);
        taMotivo.setLineWrap(true);
        taMotivo.setWrapStyleWord(true);
        taMotivo.addFocusListener(ctrlRevaluoForm);
        jScrollPane2.setViewportView(taMotivo);

        jLabel14.setText("Motivo del Revaluo:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(tfDisposicionRespaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel14)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfDepreciacionGestion, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfDespreciacionAcumulada, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfValorNeto, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(10, 10, 10)
                                .addComponent(jScrollPane2))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfCostoInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfCostoInicialNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfVidaUtil, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                            .addComponent(tfVidaUtilNuevo))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfIndiceUFV, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfIndiveUFVNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(tfCostoInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(tfVidaUtil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8)
                        .addComponent(tfIndiceUFV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tfCostoInicialNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7)
                        .addComponent(tfVidaUtilNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9)
                        .addComponent(tfIndiveUFVNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(tfDisposicionRespaldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfDepreciacionGestion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(tfDespreciacionAcumulada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(tfValorNeto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lRevaluo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lRevaluo.setForeground(new java.awt.Color(255, 0, 0));
        lRevaluo.setText("ACTIVO SIN REVALUOS TECNICOS ANTERIORES");

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        taDescripcion.setEditable(false);
        taDescripcion.setColumns(20);
        taDescripcion.setRows(5);
        taDescripcion.setLineWrap(true);
        taDescripcion.setWrapStyleWord(true);
        jScrollPane1.setViewportView(taDescripcion);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lRevaluo, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lRevaluo)
                .addGap(114, 114, 114))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(headerRevaluo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 557, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(headerRevaluo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.jc.swing.CoolButton bCancelar;
    private org.jc.swing.CoolButton bGuardar;
    private org.jc.swing.CoolButton bView;
    private datechooser.beans.DateChooserCombo dccFechaRevaluoTecnico;
    private datechooser.beans.DateChooserCombo dccIncorporacion;
    private org.jdesktop.swingx.JXHeader headerRevaluo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lRevaluo;
    private javax.swing.JTextArea taDescripcion;
    private javax.swing.JTextArea taMotivo;
    private javax.swing.JTextField tfCostoInicial;
    private javax.swing.JTextField tfCostoInicialNuevo;
    private javax.swing.JTextField tfDepreciacionGestion;
    private javax.swing.JTextField tfDespreciacionAcumulada;
    private javax.swing.JTextField tfDisposicionRespaldo;
    private javax.swing.JTextField tfIdActivoFijo;
    private javax.swing.JTextField tfIndiceUFV;
    private javax.swing.JTextField tfIndiveUFVNuevo;
    private javax.swing.JTextField tfValorNeto;
    private javax.swing.JTextField tfVidaUtil;
    private javax.swing.JTextField tfVidaUtilNuevo;
    // End of variables declaration//GEN-END:variables

    public void setObject(ActivoFijo af, Revaluo r) {
        activoFijo = af;
        revaluo = r;
        if (activoFijo != null) {
            if (activoFijo.getApiEstado().equals("ELABORADO")) {
                bGuardar.setEnabled(false);
            } else {
                bGuardar.setEnabled(true);
            }
            Calendar calendarIncorporacion = Calendar.getInstance();
            calendarIncorporacion.setTime(activoFijo.getIncorporacion());
            dccIncorporacion.setSelectedDate(calendarIncorporacion);
            tfIdActivoFijo.setText(activoFijo.getIdActivoFijo());
            taDescripcion.setText(activoFijo.getDescripcion());
            if (activoFijo.isRevaluo()) {
                lRevaluo.setText("ACTIVO CON REVALUOS TECNICOS ANTERIORES");
            } else {
                lRevaluo.setText("ACTIVO SIN REVALUOS TECNICOS ANTERIORES");
            }
            bView.setEnabled(activoFijo.isRevaluo());
            tfCostoInicial.setText(String.valueOf(activoFijo.getCostoInicial()));
            tfCostoInicialNuevo.setText(String.valueOf(revaluo.getCostoInicialNuevo()));
            tfVidaUtil.setText(String.valueOf(activoFijo.getVidaUtil()));
            tfVidaUtilNuevo.setText(String.valueOf(activoFijo.getVidaUtil()));
            tfIndiceUFV.setText(activoFijo.getIndiceUFV());
            tfIndiveUFVNuevo.setText(ViewMain.viewMain.getConfiguracion().getUFV());
            tfDisposicionRespaldo.setText(revaluo.getDisposicionRespaldo());
            tfDepreciacionGestion.setText(String.valueOf(activoFijo.getDepreciacionGestion()));
            tfDespreciacionAcumulada.setText(String.valueOf(activoFijo.getDepreciacionAcumulada()));
            tfValorNeto.setText(String.valueOf(activoFijo.getValorNeto()));
            taMotivo.setText(revaluo.getMotivo());
        } else {
            Calendar calendarIncorporacion = Calendar.getInstance();
            calendarIncorporacion.setTime(revaluo.getIncorporacion());
            dccIncorporacion.setSelectedDate(calendarIncorporacion);
            Calendar calendarRevaluoTecnico = Calendar.getInstance();
            calendarRevaluoTecnico.setTime(revaluo.getFechaRevaluoTecnico());
            dccFechaRevaluoTecnico.setSelectedDate(calendarRevaluoTecnico);
            tfIdActivoFijo.setText(revaluo.getActivoFijo().getIdActivoFijo());
            taDescripcion.setText(revaluo.getActivoFijo().getDescripcion());
            lRevaluo.setText("ACTIVO CON REVALUOS TECNICOS ANTERIORES");
            tfCostoInicial.setText(String.valueOf(revaluo.getCostoInicial()));
            tfCostoInicialNuevo.setText(String.valueOf(revaluo.getCostoInicialNuevo()));
            tfVidaUtil.setText(String.valueOf(revaluo.getVidaUtil()));
            tfVidaUtilNuevo.setText(String.valueOf(revaluo.getVidaUtilNuevo()));
            tfIndiceUFV.setText(revaluo.getIndiceUFV());
            tfIndiveUFVNuevo.setText(revaluo.getIndiceUFVNuevo());
            tfDisposicionRespaldo.setText(revaluo.getDisposicionRespaldo());
            tfDepreciacionGestion.setText(String.valueOf(revaluo.getDepreciacionGestion()));
            tfDespreciacionAcumulada.setText(String.valueOf(revaluo.getDepreciacionAcumulada()));
            tfValorNeto.setText(String.valueOf(revaluo.getValorNeto()));
            taMotivo.setText(revaluo.getMotivo());
        }
    }

    public void getObject() {
        revaluo.setIncorporacion(dccIncorporacion.getSelectedDate().getTime());
        revaluo.setFechaRevaluoTecnico(dccFechaRevaluoTecnico.getSelectedDate().getTime());
        revaluo.setCostoInicial(Double.parseDouble(tfCostoInicial.getText()));
        revaluo.setCostoInicialNuevo(Double.parseDouble(tfCostoInicialNuevo.getText()));
        revaluo.setVidaUtil(Integer.parseInt(tfVidaUtil.getText()));
        revaluo.setVidaUtilNuevo(Integer.parseInt(tfVidaUtilNuevo.getText()));
        revaluo.setIndiceUFV(tfIndiceUFV.getText());
        revaluo.setIndiceUFVNuevo(tfIndiveUFVNuevo.getText());
        revaluo.setDisposicionRespaldo(tfDisposicionRespaldo.getText());
        revaluo.setDepreciacionGestion(Double.parseDouble(tfDepreciacionGestion.getText()));
        revaluo.setDepreciacionAcumulada(Double.parseDouble(tfDespreciacionAcumulada.getText()));
        revaluo.setValorNeto(Double.parseDouble(tfValorNeto.getText()));
        revaluo.setMotivo(taMotivo.getText());
        revaluo.setUsuario(ViewMain.viewMain.getUsuario());    
        Calendar calendar  = dccFechaRevaluoTecnico.getSelectedDate();
        calendar.add(Calendar.DAY_OF_YEAR, +1);
        activoFijo.setIncorporacion(calendar.getTime());
        activoFijo.setRevaluo(true);
        activoFijo.setCostoInicial(revaluo.getCostoInicialNuevo());
        activoFijo.setVidaUtil(revaluo.getVidaUtilNuevo());
        activoFijo.setIndiceUFV(revaluo.getIndiceUFVNuevo());
        activoFijo.setUsuario(ViewMain.viewMain.getUsuario());
        revaluo.setActivoFijo(activoFijo);
        int option = JOptionPane.showConfirmDialog(ViewMain.viewMain, "Esta seguro de los datos que se quiere revaluar?", "Mensaje", JOptionPane.YES_NO_OPTION);
        if (option == JOptionPane.YES_OPTION) {
            ViewMain.DAO.add(revaluo);
            ViewMain.DAO.update(activoFijo);
            ActivoFijoForm.activoFijoForm.setObject(activoFijo);
            ActivoFijoView.activoFijoView.getActivoFijoTable().reload();
            ActivoFijoView.activoFijoView.getDialog().dispose();
        }
    }

    private class CtrlRevaluoForm implements ActionListener, FocusListener {

        @Override
        public void actionPerformed(ActionEvent e) {
            Object aux = e.getSource();
            if (aux.equals(bGuardar)) {
                getObject();
            } else if (aux.equals(bCancelar)) {
                ActivoFijoView.activoFijoView.getDialog().dispose();
            } else if (aux.equals(bView)) {
                Revaluo rev = new Revaluo();
                rev.setActivoFijo(activoFijo);
                RevaluoView.revaluoView.setRevaluo(rev);
                RevaluoView.revaluoView.getRevaluoTable().reload();
                ActivoFijoView.activoFijoView.getDialog().dispose();
                ActivoFijoView.activoFijoView.getCommonDialog().dispose();
                ViewMain.viewMain.getDockableRevaluo().setTitleText("Revaluos del Activo - " + activoFijo.getIdActivoFijo());
                ViewMain.viewMain.getFrontend().hide(ViewMain.viewMain.getDockableRevaluo());
                ViewMain.viewMain.getFrontend().show(ViewMain.viewMain.getDockableRevaluo());
            }
        }

        @Override
        public void focusGained(FocusEvent e) {
            Object aux = e.getSource();
            if (aux.equals(tfCostoInicialNuevo)) {
                tfCostoInicialNuevo.selectAll();
            } else if (aux.equals(tfVidaUtilNuevo)) {
                tfVidaUtilNuevo.selectAll();
            } else if (aux.equals(tfDisposicionRespaldo)) {
                tfDisposicionRespaldo.selectAll();
            } else if (aux.equals(taMotivo)) {
                taMotivo.selectAll();
            }
        }

        @Override
        public void focusLost(FocusEvent e) {
        }
    }
}
