/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view.activos;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import model.domain.ActivoFijo;
import view.ViewMain;

/**
 *
 * SearchForm
 *
 * @author Sergio Antonio Ochoa Martinez - gnu.java.sergio@gmail.com
 * @version 0.1
 */
public class SearchForm extends javax.swing.JPanel {

    private CtrlSearchForm ctrlSearchForm;

    /**
     * SearchForm
     */
    public SearchForm() {
        ctrlSearchForm = new CtrlSearchForm();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelCurves1 = new org.jc.swing.panel.PanelCurves();
        jPanel1 = new javax.swing.JPanel();
        bSearch = new org.jc.swing.CoolButton(0);
        bCancel = new org.jc.swing.CoolButton(0);
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tfIdActivoFijo = new javax.swing.JTextField();
        headerActivoFijo = new org.jdesktop.swingx.JXHeader();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 20, 10));

        bSearch.setText("Buscar");
        bSearch.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        bSearch.addActionListener(ctrlSearchForm);
        bSearch.addKeyListener(ctrlSearchForm);
        jPanel1.add(bSearch);

        bCancel.setText("Cancel");
        bCancel.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        bCancel.addActionListener(ctrlSearchForm);
        bCancel.addActionListener(ctrlSearchForm);
        jPanel1.add(bCancel);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Codigo:");

        tfIdActivoFijo.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        tfIdActivoFijo.addKeyListener(ctrlSearchForm);
        tfIdActivoFijo.addFocusListener(ctrlSearchForm);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addGap(34, 34, 34)
                .addComponent(tfIdActivoFijo, javax.swing.GroupLayout.PREFERRED_SIZE, 471, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfIdActivoFijo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelCurves1Layout = new javax.swing.GroupLayout(panelCurves1);
        panelCurves1.setLayout(panelCurves1Layout);
        panelCurves1Layout.setHorizontalGroup(
            panelCurves1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCurves1Layout.createSequentialGroup()
                .addGroup(panelCurves1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCurves1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelCurves1Layout.setVerticalGroup(
            panelCurves1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCurves1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(panelCurves1, java.awt.BorderLayout.CENTER);

        headerActivoFijo.setDescription("");
        headerActivoFijo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/entidad.png"))); // NOI18N
        headerActivoFijo.setIconPosition(org.jdesktop.swingx.JXHeader.IconPosition.LEFT);
        headerActivoFijo.setTitle("Busquedas por el Codigo");
        headerActivoFijo.setTitleFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        add(headerActivoFijo, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.jc.swing.CoolButton bCancel;
    private org.jc.swing.CoolButton bSearch;
    private org.jdesktop.swingx.JXHeader headerActivoFijo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private org.jc.swing.panel.PanelCurves panelCurves1;
    private javax.swing.JTextField tfIdActivoFijo;
    // End of variables declaration//GEN-END:variables

    public void addSearch() {
        ActivoFijo activoFijo = new ActivoFijo();
        activoFijo.setIdActivoFijo(tfIdActivoFijo.getText());
        activoFijo = (ActivoFijo) ViewMain.DAO.getObject(activoFijo);
        if (activoFijo != null) {
            ActivoFijoForm.activoFijoForm.setObject(activoFijo);
            ActivoFijoForm.activoFijoForm.getCommonDialog().dispose();
        } else {
            JOptionPane.showMessageDialog(ViewMain.viewMain, "El activo fijo que esta buscando no se encuentra registrado, Intentelo nuevamente", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
        }
    }

    private class CtrlSearchForm extends KeyAdapter implements ActionListener, FocusListener {

        @Override
        public void actionPerformed(ActionEvent e) {
            Object aux = e.getSource();
            if (aux.equals(bSearch)) {
                addSearch();
            } else if (aux.equals(bCancel)) {
                ActivoFijoForm.activoFijoForm.getCommonDialog().dispose();
            }

        }

        @Override
        public void keyPressed(KeyEvent e) {
            if (e.getKeyCode() == 10) {
                if (tfIdActivoFijo.isFocusable()) {
                    addSearch();
                } else if (bSearch.isFocusable()) {
                    addSearch();
                } else if (bCancel.isFocusable()) {
                    ActivoFijoForm.activoFijoForm.getCommonDialog().dispose();
                }
            }
        }

        @Override
        public void focusGained(FocusEvent e) {
            tfIdActivoFijo.selectAll();
        }

        @Override
        public void focusLost(FocusEvent e) {
        }
    }
}
