package view.seguridad;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.awt.image.BufferedImage;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import jdbc.Conexion;
import model.dao.CommonDAO;
import model.domain.Usuario;
import view.ViewMain;

/**
 * Autentificarse
 *
 * @author Sergio Antonio Ochoa Martinez - gnu.java.sergio@gmail.com
 * @version 0.3
 */
public class Autentificarse extends javax.swing.JDialog {

    private Dimension screenSize;
    private ViewMain viewMain;
    private Conexion conexion;
    private CommonDAO dao;
    private CtrlAutentificarse ctrlAutentificarse;
    private BufferedImage foto;

    /**
     * Autentificarse
     */
    public Autentificarse(JFrame parent, boolean modal, Conexion conexion) {
        super(parent, modal);
        this.conexion = conexion;
        this.ctrlAutentificarse = new CtrlAutentificarse();
        this.dao = new CommonDAO(this.conexion, CommonDAO.HSQLDB);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headerAutentificarse = new org.jdesktop.swingx.JXHeader();
        panelCurves1 = new org.jc.swing.panel.PanelCurves();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tfLogin = new javax.swing.JTextField();
        pfPassword = new javax.swing.JPasswordField();
        jPanel2 = new javax.swing.JPanel();
        bEntrar = new javax.swing.JButton();
        bSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        headerAutentificarse.setDescription("");
        headerAutentificarse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/usuario.png"))); // NOI18N
        headerAutentificarse.setTitle("Autentificarse");
        headerAutentificarse.setTitleFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        getContentPane().add(headerAutentificarse, java.awt.BorderLayout.PAGE_START);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("Login");

        jLabel2.setText("Contaseña:");

        tfLogin.addKeyListener(ctrlAutentificarse);

        pfPassword.addKeyListener(ctrlAutentificarse);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfLogin)
                    .addComponent(pfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(pfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        bEntrar.setText("Entrar");
        bEntrar.setSelected(true);
        bEntrar.addActionListener(ctrlAutentificarse);
        bEntrar.addKeyListener(ctrlAutentificarse);
        jPanel2.add(bEntrar);

        bSalir.setText("Salir");
        bSalir.setSelected(true);
        bSalir.addActionListener(ctrlAutentificarse);
        jPanel2.add(bSalir);

        javax.swing.GroupLayout panelCurves1Layout = new javax.swing.GroupLayout(panelCurves1);
        panelCurves1.setLayout(panelCurves1Layout);
        panelCurves1Layout.setHorizontalGroup(
            panelCurves1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCurves1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCurves1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 344, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelCurves1Layout.setVerticalGroup(
            panelCurves1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCurves1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        getContentPane().add(panelCurves1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bEntrar;
    private javax.swing.JButton bSalir;
    private org.jdesktop.swingx.JXHeader headerAutentificarse;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private org.jc.swing.panel.PanelCurves panelCurves1;
    private javax.swing.JPasswordField pfPassword;
    private javax.swing.JTextField tfLogin;
    // End of variables declaration//GEN-END:variables

    public void addEntrar() {
        Usuario usuario = new Usuario();
        usuario.setLogin(this.tfLogin.getText());
        usuario.setPassword(this.pfPassword.getText());

        if (((Usuario) dao.getObject(usuario)).getIdUsuario() != 0) {
            setVisible(false);
            this.screenSize = Toolkit.getDefaultToolkit().getScreenSize();
            this.viewMain = new ViewMain(dao, usuario,conexion);
            this.viewMain.setTitle("Sistema de Activos Fijo - Gobierno Autonomo Municipal de Presto");
            this.viewMain.setSize(screenSize.width, screenSize.height - 30);
            this.viewMain.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this.rootPane, "El usuario no es el correcto", "Mensaje", JOptionPane.ERROR_MESSAGE);
        }
    }

    private class CtrlAutentificarse extends KeyAdapter implements ActionListener {

        private CtrlAutentificarse() {
        }

        @Override
        public void actionPerformed(ActionEvent e) {
            Object aux = e.getSource();
            if (aux.equals(bEntrar)) {
                addEntrar();
            } else if (aux.equals(bSalir)) {
                System.exit(0);
            }
        }

        @Override
        public void keyPressed(KeyEvent e) {
            if (e.getKeyCode() == 10) {
                if (bEntrar.isFocusable()) {
                    addEntrar();
                } else if (pfPassword.isFocusable()) {
                    addEntrar();
                } else if (tfLogin.isFocusable()) {
                    addEntrar();
                }
            }
        }
    }
}