/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view.seguridad;

import java.awt.BorderLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import model.domain.Usuario;
import utils.IconUI;
import view.ViewMain;
import view.common.CommonDialog;
import view.common.CommonView;

/**
 * UsuarioView
 *
 * @author Sergio Antonio Ochoa Martinez - gnu.java.sergio@gmail.com
 * @version 0.1
 */
public class UsuarioView extends javax.swing.JPanel implements CommonView {

    private CtrlUsuarioView ctrlUsuarioView;
    private UsuarioForm usuarioForm;
    private UsuarioTable usuarioTable;
    public static UsuarioView usuarioView;

    public UsuarioView() {
        usuarioView = this;
        ctrlUsuarioView = new CtrlUsuarioView();
        initComponents();
        usuarioForm = new UsuarioForm(new Usuario());
        usuarioTable = new UsuarioTable();
        this.add(usuarioTable, BorderLayout.CENTER);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        bNew = new org.jc.swing.CoolButton(1);
        bUpdate = new org.jc.swing.CoolButton(2);
        bDelete = new org.jc.swing.CoolButton(2);

        setLayout(new java.awt.BorderLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 0, 5));

        bNew.setText("Nuevo");
        bNew.setIcon(IconUI.getResizableIcon("add", 32,32));
        bNew.addActionListener(ctrlUsuarioView);
        jPanel1.add(bNew);

        bUpdate.setText("Editar");
        bUpdate.setIcon(IconUI.getResizableIcon("update", 32, 32));
        jPanel1.add(bUpdate);
        bUpdate.addActionListener(ctrlUsuarioView);

        bDelete.setText("Borrar");
        bDelete.setIcon(IconUI.getResizableIcon("delete", 32, 32));
        jPanel1.add(bDelete);
        bDelete.addActionListener(ctrlUsuarioView);

        add(jPanel1, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.jc.swing.CoolButton bDelete;
    private org.jc.swing.CoolButton bNew;
    private org.jc.swing.CoolButton bUpdate;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
    public UsuarioTable getUsuarioTable() {
        return usuarioTable;
    }

    @Override
    public void addNew() {
        ViewMain.viewMain.getGlassPane().setVisible(true);
        ViewMain.viewMain.setCommonDialog(new CommonDialog(ViewMain.viewMain, true));
        ViewMain.viewMain.getCommonDialog().setTitle("Nueva Usuario");
        usuarioForm.setObject(new Usuario());
        usuarioForm.getbGuardar().setText("Guardar");
        usuarioForm.getHeaderUsuario().setDescription("Introducir los datos del Usuario");
        ViewMain.viewMain.getCommonDialog().add(usuarioForm);
        ViewMain.viewMain.getCommonDialog().visibleDialog("Nuevo Usuario");
        ViewMain.viewMain.getGlassPane().setVisible(false);
    }

    @Override
    public void addUpdate() {
        ViewMain.viewMain.getGlassPane().setVisible(true);
        ViewMain.viewMain.setCommonDialog(new CommonDialog(ViewMain.viewMain, true));
        Usuario usuario = new Usuario();
        usuario = (Usuario) usuarioTable.getSelectedObject(usuario);
        if (usuario != null) {
            usuario = (Usuario) ViewMain.DAO.getObject(usuario);
            usuarioForm.setObject(usuario);
            usuarioForm.getbGuardar().setText("Actualizar");
            usuarioForm.getHeaderUsuario().setDescription("Modificar los datos del Usuario");            
            ViewMain.viewMain.getCommonDialog().add(usuarioForm);
            ViewMain.viewMain.getCommonDialog().visibleDialog("Actualizando " + usuario.getNombres());
            ViewMain.viewMain.getGlassPane().setVisible(false);
        } else {
            JOptionPane.showMessageDialog(ViewMain.viewMain, "No selecciono ninguna Usuario", "Mensaje", 0);
            ViewMain.viewMain.getGlassPane().setVisible(false);
        }
    }

    @Override
    public void addDelete() {
        Usuario usuario = new Usuario();
        usuario = (Usuario) usuarioTable.getSelectedObject(usuario);
        if (usuario != null) {
            int option = JOptionPane.showConfirmDialog(ViewMain.viewMain, "Esta seguro que desea borrar la Usuario", "Borrar", 0);
            if (option == 0) {
                ViewMain.DAO.delete(usuario);
                usuarioTable.reload();
            }
        } else {
            JOptionPane.showMessageDialog(ViewMain.viewMain, "No selecciono ninguna usuario", "Borrar", 0);
        }
    }

    private class CtrlUsuarioView implements ActionListener {

        @Override
        public void actionPerformed(ActionEvent e) {
            Object aux = e.getSource();
            if (aux.equals(bNew)) {
                addNew();
            } else if (aux.equals(bUpdate)) {
                addUpdate();
            } else if (aux.equals(bDelete)) {
                addDelete();
            }
        }
    }
}