/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view.administracion;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import model.domain.Auxiliar;
import model.domain.Grupo;
import org.jc.swing.CoolButton;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;
import utils.IconUI;
import view.ViewMain;
import view.common.CommonForm;

/**
 * AuxiliarForm
 *
 * @author Sergio Antonio Ochoa Martinez gnu.java.sergio@gmail.com
 * @version 0.2
 */
public class AuxiliarForm extends javax.swing.JPanel implements CommonForm {

    public static AuxiliarForm auxiliarForm;
    private Auxiliar auxiliar;
    private CtrlAuxiliarForm ctrlAuxiliarForm;
    private DefaultComboBoxModel comboBoxModelGrupo;

    /**
     * Auxiliar
     */
    public AuxiliarForm() {
        auxiliarForm = this;
        ctrlAuxiliarForm = new CtrlAuxiliarForm();
        initComponents();
    }

    public CoolButton getbGuardar() {
        return bGuardar;
    }

    public void initComboBoxGrupo(java.util.List list) {
        comboBoxModelGrupo = new DefaultComboBoxModel();
        comboBoxModelGrupo.removeAllElements();
        for (Object o : list) {
            comboBoxModelGrupo.addElement((Grupo) o);
        }
        cbGrupo.setModel(comboBoxModelGrupo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        bGuardar = new org.jc.swing.CoolButton(0);
        bCancelar = new org.jc.swing.CoolButton(0);
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tfNombre = new javax.swing.JTextField();
        cbGrupo = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        bGuardar.setText("Guardar");
        bGuardar.addActionListener(ctrlAuxiliarForm);
        bGuardar.setIcon(IconUI.getResizableIcon("aceptar", 32, 32));
        jPanel2.add(bGuardar);

        bCancelar.setText("Cancelar");
        bCancelar.addActionListener(ctrlAuxiliarForm);
        bCancelar.setIcon(IconUI.getResizableIcon("cancelar", 32, 32));
        jPanel2.add(bCancelar);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Oficina"));

        jLabel1.setText("Nombre Auxiliar:");

        tfNombre.addFocusListener(ctrlAuxiliarForm);
        tfNombre.addKeyListener(ctrlAuxiliarForm);

        jLabel2.setText("Grupo.");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cbGrupo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tfNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 451, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.jc.swing.CoolButton bCancelar;
    private org.jc.swing.CoolButton bGuardar;
    private javax.swing.JComboBox cbGrupo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField tfNombre;
    // End of variables declaration//GEN-END:variables

    @Override
    public Object getObject() {
        auxiliar.setNombre(tfNombre.getText());
        auxiliar.setUsuario(ViewMain.viewMain.getUsuario());
        auxiliar.setGrupo((Grupo) cbGrupo.getSelectedItem());
        auxiliar.setUnidad(ViewMain.viewMain.getUnidad());
        return auxiliar;
    }

    @Override
    public void setObject(Object obj) {
        auxiliar = (Auxiliar) obj;
        if (auxiliar.getIdAuxiliar() == 0) {
            cbGrupo.setSelectedIndex(0);
        } else {
            comboBoxModelGrupo.setSelectedItem(auxiliar.getGrupo());
        }
        tfNombre.setText(auxiliar.getNombre());
    }

    public void addSave() {
        auxiliar = (Auxiliar) getObject();
        List list = ViewMain.DAO.select(auxiliar);
        if (list.isEmpty()) {
            if (bGuardar.getText().equals("Guardar")) {
                ViewMain.DAO.add(auxiliar);
            } else {
                ViewMain.DAO.update(auxiliar);
            }
            AuxiliarView.auxiliarView.getAuxiliarTable().reload();
            ViewMain.viewMain.getCommonDialog().dispose();
        } else {
            JOptionPane.showMessageDialog(ViewMain.viewMain, "El nombre del Auxiliar ya exite en esta Unidad.", "Mensaje", JOptionPane.ERROR_MESSAGE);
        }

    }

    private class CtrlAuxiliarForm extends KeyAdapter implements ActionListener, FocusListener {

        @Override
        public void actionPerformed(ActionEvent e) {
            Object aux = e.getSource();
            if (aux.equals(bGuardar)) {
                addSave();
            } else if (aux.equals(bCancelar)) {
                ViewMain.viewMain.getCommonDialog().dispose();
            }
        }

        @Override
        public void focusGained(FocusEvent e) {
            tfNombre.selectAll();
        }

        @Override
        public void focusLost(FocusEvent e) {
        }

        @Override
        public void keyPressed(KeyEvent e) {
            if (e.getKeyCode() == 10) {
                addSave();
            }
        }
    }
}