/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view.administracion;

import java.awt.BorderLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import model.domain.Grupo;
import utils.IconUI;
import view.ViewMain;
import view.common.CommonDialog;
import view.common.CommonView;

/**
 * GrupoView
 *
 * @author Sergio Antonio Ochoa Martinez - gnu.java.sergio@gmail.com
 * @version 0.1
 */
public class GrupoView extends javax.swing.JPanel implements CommonView {

    private GrupoView.CtrlGrupoView ctrlGrupoView;
    private GrupoForm grupoForm;
    private GrupoTable grupoTable;
    public static GrupoView grupoView;
    private CommonDialog commonDialog;

    public GrupoView() {
        grupoView = this;
        ctrlGrupoView = new CtrlGrupoView();
        initComponents();
        grupoForm = new GrupoForm(new Grupo());
        grupoTable = new GrupoTable();
        this.add(grupoTable, BorderLayout.CENTER);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        bNew = new org.jc.swing.CoolButton(1);
        bUpdate = new org.jc.swing.CoolButton(2);
        bDelete = new org.jc.swing.CoolButton(2);
        bSearch = new org.jc.swing.CoolButton(0);

        setLayout(new java.awt.BorderLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 0, 5));

        bNew.setText("Nuevo");
        bNew.setIcon(IconUI.getResizableIcon("add", 32,32));
        bNew.addActionListener(ctrlGrupoView);
        bNew.setVisible(false);
        jPanel1.add(bNew);

        bUpdate.setText("Editar");
        bUpdate.setIcon(IconUI.getResizableIcon("update", 32, 32));
        jPanel1.add(bUpdate);
        bUpdate.addActionListener(ctrlGrupoView);
        bUpdate.setVisible(false);

        bDelete.setText("Borrar");
        bDelete.setIcon(IconUI.getResizableIcon("delete", 32, 32));
        jPanel1.add(bDelete);
        bDelete.addActionListener(ctrlGrupoView);
        bDelete.setVisible(false);

        bSearch.setText("Buscar");
        bSearch.setIcon(IconUI.getResizableIcon("search", 32, 32));
        bSearch.setVisible(false);
        jPanel1.add(bSearch);
        bSearch.addActionListener(ctrlGrupoView);

        add(jPanel1, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.jc.swing.CoolButton bDelete;
    private org.jc.swing.CoolButton bNew;
    private org.jc.swing.CoolButton bSearch;
    private org.jc.swing.CoolButton bUpdate;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    public CommonDialog getCommonDialog() {
        return commonDialog;
    }

    public GrupoTable getGrupoTable() {
        return grupoTable;
    }

    @Override
    public void addNew() {
        ViewMain.viewMain.getGlassPane().setVisible(true);
        commonDialog = new CommonDialog(ViewMain.viewMain, true);
        commonDialog.setTitle("Nueva Grupo");
        grupoForm.setObject(new Grupo());
        grupoForm.getbGuardar().setText("Guardar");
        commonDialog.add(grupoForm);
        commonDialog.visibleDialog("Nuevo Grupo");
        ViewMain.viewMain.getGlassPane().setVisible(false);
    }

    @Override
    public void addUpdate() {
        ViewMain.viewMain.getGlassPane().setVisible(true);
        commonDialog = new CommonDialog(ViewMain.viewMain, true);
        Grupo grupo = new Grupo();
        grupo = (Grupo) grupoTable.getSelectedObject(grupo);
        if (grupo != null) {
            grupo = (Grupo) ViewMain.DAO.getObject(grupo);
            grupoForm.setObject(grupo);
            grupoForm.getbGuardar().setText("Actualizar");            
            commonDialog.add(grupoForm);
            commonDialog.visibleDialog("Actualizando " + grupo.getNombre());
            ViewMain.viewMain.getGlassPane().setVisible(false);
        } else {
            JOptionPane.showMessageDialog(ViewMain.viewMain, "No selecciono ninguna Grupo", "Mensaje", 0);
            ViewMain.viewMain.getGlassPane().setVisible(false);
        }
    }

    @Override
    public void addDelete() {
        Grupo grupo = new Grupo();
        grupo = (Grupo) grupoTable.getSelectedObject(grupo);
        if (grupo != null) {
            int option = JOptionPane.showConfirmDialog(ViewMain.viewMain, "Esta seguro que desea borrar la Grupo", "Borrar", 0);
            if (option == 0) {
                ViewMain.DAO.delete(grupo);
                grupoTable.reload();
            }
        } else {
            JOptionPane.showMessageDialog(ViewMain.viewMain, "No selecciono ninguna grupo", "Borrar", 0);
        }
    }

    private class CtrlGrupoView implements ActionListener {

        @Override
        public void actionPerformed(ActionEvent e) {
            Object aux = e.getSource();
            if (aux.equals(bNew)) {
                addNew();
            } else if (aux.equals(bUpdate)) {
                addUpdate();
            } else if (aux.equals(bDelete)) {
                addDelete();
            }
        }
    }
}
