/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view.administracion;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import model.domain.Grupo;
import org.jc.swing.CoolButton;
import org.jc.swing.JCTextField;
import utils.IconUI;
import view.ViewMain;
import view.common.CommonForm;

/**
 * GrupoForm
 *
 * @author Sergio Antonio Ochoa Martinez gnu.java.sergio@gmail.com
 * @version 0.2
 */
public class GrupoForm extends javax.swing.JPanel implements CommonForm {

    private Grupo grupo;
    private CtrlGrupoForm ctrlGrupoForm;

    /**
     * Grupo
     */
    public GrupoForm(Grupo grupo) {
        this.grupo = grupo;
        ctrlGrupoForm = new CtrlGrupoForm();
        initComponents();
    }

    public CoolButton getbGuardar() {
        return bGuardar;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        bGuardar = new org.jc.swing.CoolButton(0);
        bCancelar = new org.jc.swing.CoolButton(0);
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tfNombre = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        taObservacion = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        tfVidaUtil = new JCTextField(JCTextField.NUMERICO);
        cbDepreciar = new javax.swing.JCheckBox();
        cbActualizar = new javax.swing.JCheckBox();

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        bGuardar.setText("Guardar");
        bGuardar.addActionListener(ctrlGrupoForm);
        bGuardar.setIcon(IconUI.getResizableIcon("aceptar", 32, 32));
        jPanel2.add(bGuardar);

        bCancelar.setText("Cancelar");
        bCancelar.addActionListener(ctrlGrupoForm);
        bCancelar.setIcon(IconUI.getResizableIcon("cancelar", 32, 32));
        jPanel2.add(bCancelar);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Oficina"));

        jLabel1.setText("Nombre:");

        jLabel2.setText("Observacion:");

        tfNombre.addFocusListener(ctrlGrupoForm);

        taObservacion.setColumns(20);
        taObservacion.addFocusListener(ctrlGrupoForm);
        taObservacion.setRows(5);
        taObservacion.setLineWrap(true);
        taObservacion.setWrapStyleWord(true);
        jScrollPane1.setViewportView(taObservacion);

        jLabel3.setText("Vida Util:");

        tfVidaUtil.addFocusListener(ctrlGrupoForm);

        cbDepreciar.setText("Depreciar");

        cbActualizar.setText("Actualizar");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfNombre)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
                    .addComponent(tfVidaUtil)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(cbDepreciar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cbActualizar)
                        .addGap(20, 20, 20)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfVidaUtil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbDepreciar)
                    .addComponent(cbActualizar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.jc.swing.CoolButton bCancelar;
    private org.jc.swing.CoolButton bGuardar;
    private javax.swing.JCheckBox cbActualizar;
    private javax.swing.JCheckBox cbDepreciar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea taObservacion;
    private javax.swing.JTextField tfNombre;
    private javax.swing.JTextField tfVidaUtil;
    // End of variables declaration//GEN-END:variables
    @Override
    public Object getObject() {
        grupo.setNombre(tfNombre.getText());
        grupo.setObservacion(taObservacion.getText());
        grupo.setVidaUtil(Integer.parseInt(tfVidaUtil.getText()));
        grupo.setDepreciar(cbDepreciar.isSelected());
        grupo.setActualizar(cbActualizar.isSelected());
        grupo.setUsuario(ViewMain.viewMain.getUsuario());       
        return grupo;
    }

    @Override
    public void setObject(Object obj) {
        grupo = (Grupo) obj;        
        tfNombre.setText(grupo.getNombre());
        taObservacion.setText(grupo.getObservacion());
        tfVidaUtil.setText(String.valueOf(grupo.getVidaUtil()));
        cbDepreciar.setSelected(grupo.isDepreciar());
        cbActualizar.setSelected(grupo.isActualizar());
    }

    private class CtrlGrupoForm implements ActionListener, FocusListener {

        @Override
        public void actionPerformed(ActionEvent e) {
            Object aux = e.getSource();
            if (aux.equals(bGuardar)) {

                grupo = (Grupo) getObject();
                if (bGuardar.getText().equals("Guardar")) {
                    ViewMain.DAO.add(grupo);
                } else {
                    ViewMain.DAO.update(grupo);
                }
                GrupoView.grupoView.getGrupoTable().reload();
                GrupoView.grupoView.getCommonDialog().dispose();
            } else if (aux.equals(bCancelar)) {
                GrupoView.grupoView.getCommonDialog().dispose();
            }
        }

        @Override
        public void focusGained(FocusEvent e) {
           Object aux = e.getSource();
           if(aux.equals(tfNombre)){
               tfNombre.selectAll();
           } else if(aux.equals(tfVidaUtil)){
               tfVidaUtil.selectAll();
           } else if(aux.equals(taObservacion)){
               taObservacion.selectAll();
           }
        }

        @Override
        public void focusLost(FocusEvent e) {
            
        }
    }
}