/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view.administracion;

import java.awt.BorderLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import model.domain.Oficina;
import utils.IconUI;
import view.ViewMain;
import view.common.CommonDialog;
import view.common.CommonView;

/**
 * OficinaView
 *
 * @author Sergio Antonio Ochoa Martinez - gnu.java.sergio@gmail.com
 * @version 0.1
 */
public class OficinaView extends javax.swing.JPanel implements CommonView {

    private CtrlOficinaView ctrlOficinaView;
    private OficinaForm oficinaForm;
    private OficinaTable oficinaTable;
    public static OficinaView oficinaView;

    public OficinaView() {
        oficinaView = this;
        ctrlOficinaView = new CtrlOficinaView();
        initComponents();
        oficinaForm = new OficinaForm(new Oficina());
        oficinaTable = new OficinaTable();
        this.add(oficinaTable, BorderLayout.CENTER);       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        bNew = new org.jc.swing.CoolButton(1);
        bUpdate = new org.jc.swing.CoolButton(2);
        bDelete = new org.jc.swing.CoolButton(2);

        setLayout(new java.awt.BorderLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 0, 5));

        bNew.setText("Nuevo");
        bNew.setIcon(IconUI.getResizableIcon("add", 32,32));
        bNew.addActionListener(ctrlOficinaView);
        jPanel1.add(bNew);

        bUpdate.setText("Editar");
        bUpdate.setIcon(IconUI.getResizableIcon("update", 32, 32));
        jPanel1.add(bUpdate);
        bUpdate.addActionListener(ctrlOficinaView);

        bDelete.setText("Borrar");
        bDelete.setIcon(IconUI.getResizableIcon("delete", 32, 32));
        jPanel1.add(bDelete);
        bDelete.addActionListener(ctrlOficinaView);

        add(jPanel1, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.jc.swing.CoolButton bDelete;
    private org.jc.swing.CoolButton bNew;
    private org.jc.swing.CoolButton bUpdate;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    public OficinaTable getOficinaTable() {
        return oficinaTable;
    }

    @Override
    public void addNew() {
        ViewMain.viewMain.getGlassPane().setVisible(true);
        ViewMain.viewMain.setCommonDialog(new CommonDialog(ViewMain.viewMain, true));
        ViewMain.viewMain.getCommonDialog().setTitle("Nueva Oficina");
        oficinaForm.setObject(new Oficina());
        oficinaForm.getbGuardar().setText("Guardar");
        ViewMain.viewMain.getCommonDialog().add(oficinaForm);
        ViewMain.viewMain.getCommonDialog().visibleDialog("Nueva Oficina");
        ViewMain.viewMain.getGlassPane().setVisible(false);
    }

    @Override
    public void addUpdate() {
        ViewMain.viewMain.getGlassPane().setVisible(true);
        ViewMain.viewMain.setCommonDialog(new CommonDialog(ViewMain.viewMain, true));
        Oficina oficina = new Oficina();
        oficina = (Oficina) oficinaTable.getSelectedObject(oficina);
        if (oficina != null) {
            oficina = (Oficina) ViewMain.DAO.getObject(oficina);
            oficinaForm.setObject(oficina);
            oficinaForm.getbGuardar().setText("Actualizar");
            ViewMain.viewMain.getCommonDialog().add(oficinaForm);
            ViewMain.viewMain.getCommonDialog().visibleDialog("Actualizando " + oficina.getNombre());
            ViewMain.viewMain.getGlassPane().setVisible(false);
        } else {
            JOptionPane.showMessageDialog(ViewMain.viewMain, "No selecciono ninguna Oficina", "Mensaje", 0);
            ViewMain.viewMain.getGlassPane().setVisible(false);
        }
    }

    @Override
    public void addDelete() {
        Oficina oficina = new Oficina();
        oficina = (Oficina) oficinaTable.getSelectedObject(oficina);
        if (oficina != null) {
            int option = JOptionPane.showConfirmDialog(ViewMain.viewMain, "Esta seguro que desea borrar la Oficina", "Borrar", 0);
            if (option == 0) {
                ViewMain.DAO.delete(oficina);
                oficinaTable.reload();
            }
        } else {
            JOptionPane.showMessageDialog(ViewMain.viewMain, "No selecciono ninguna oficina", "Borrar", 0);
        }
    }

    private class CtrlOficinaView implements ActionListener {

        @Override
        public void actionPerformed(ActionEvent e) {
            Object aux = e.getSource();
            if (aux.equals(bNew)) {
                addNew();
            } else if (aux.equals(bUpdate)) {
                addUpdate();
            } else if (aux.equals(bDelete)) {
                addDelete();
            }
        }
    }
}
