/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view.administracion;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import javax.swing.DefaultComboBoxModel;
import model.domain.Oficina;
import model.domain.Responsable;
import org.jc.swing.CoolButton;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;
import utils.IconUI;
import view.ViewMain;
import view.common.CommonForm;

/**
 * CommonForm
 *
 * @author Sergio Antonio Ochoa Martinez - gnu.java.sergio@gmail.com
 * @version 0.3
 */
public class ResponsableForm extends javax.swing.JPanel implements CommonForm {

    private Responsable responsable;
    private ResponsableForm.CtrlResponsableForm ctrlResponsableForm;
    private DefaultComboBoxModel comboBoxModelOficina;

    /**
     * Responsable
     */
    public ResponsableForm(Responsable responsable) {
        this.responsable = responsable;
        ctrlResponsableForm = new CtrlResponsableForm();
        initComponents();
    }

    public CoolButton getbGuardar() {
        return bGuardar;
    }

    public void initComboBoxOficina(java.util.List list) {
        comboBoxModelOficina = new DefaultComboBoxModel();
        comboBoxModelOficina.removeAllElements();
        for (Object o : list) {
            comboBoxModelOficina.addElement((Oficina) o);
        }
        cbOficina.setModel(comboBoxModelOficina);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        bGuardar = new org.jc.swing.CoolButton(0);
        bCancelar = new org.jc.swing.CoolButton(0);
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tfNombre = new javax.swing.JTextField();
        tfCi = new javax.swing.JTextField();
        tfCargo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cbOficina = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        bGuardar.setText("Guardar");
        bGuardar.addActionListener(ctrlResponsableForm);
        bGuardar.setIcon(IconUI.getResizableIcon("aceptar", 32, 32));
        bGuardar.addKeyListener(ctrlResponsableForm);
        jPanel2.add(bGuardar);

        bCancelar.setText("Cancelar");
        bCancelar.addActionListener(ctrlResponsableForm);
        bCancelar.setIcon(IconUI.getResizableIcon("cancelar", 32, 32));
        jPanel2.add(bCancelar);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Responsable"));

        jLabel1.setText("Nombre:");

        jLabel2.setText("CI:");

        tfNombre.addFocusListener(ctrlResponsableForm);

        tfCi.addFocusListener(ctrlResponsableForm);

        tfCargo.addFocusListener(ctrlResponsableForm);

        jLabel3.setText("Cargo:");

        jLabel4.setText("Grupo:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cbOficina, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tfNombre)
                    .addComponent(tfCi)
                    .addComponent(tfCargo, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbOficina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfCi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.jc.swing.CoolButton bCancelar;
    private org.jc.swing.CoolButton bGuardar;
    private javax.swing.JComboBox cbOficina;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField tfCargo;
    private javax.swing.JTextField tfCi;
    private javax.swing.JTextField tfNombre;
    // End of variables declaration//GEN-END:variables

    @Override
    public Object getObject() {
        responsable.setNombre(tfNombre.getText());
        responsable.setCi(tfCi.getText());
        responsable.setCargo(tfCargo.getText());
        responsable.setUsuario(ViewMain.viewMain.getUsuario());
        responsable.setOficina((Oficina) cbOficina.getSelectedItem());
        return responsable;
    }

    @Override
    public void setObject(Object obj) {
        responsable = (Responsable) obj;
        if (responsable.getIdResponsable() == 0) {
            cbOficina.setSelectedIndex(0);
        } else {
            comboBoxModelOficina.setSelectedItem(responsable.getOficina());
        }
        tfNombre.setText(responsable.getNombre());
        tfCi.setText(responsable.getCi());
        tfCargo.setText(responsable.getCargo());
    }

    public void addSave() {
        responsable = (Responsable) getObject();
        if (ResponsableForm.this.bGuardar.getText().equals("Guardar")) {
            ViewMain.DAO.add(responsable);
        } else {
            ViewMain.DAO.update(ResponsableForm.this.responsable);
        }
        ResponsableView.responsableView.getResponsableTable().reload();
        ViewMain.viewMain.getCommonDialog().dispose();
    }

    private class CtrlResponsableForm extends KeyAdapter implements ActionListener, FocusListener {

        @Override
        public void actionPerformed(ActionEvent e) {
            Object aux = e.getSource();
            if (aux.equals(bGuardar)) {
                addSave();
            } else if (aux.equals(ResponsableForm.this.bCancelar)) {
                ViewMain.viewMain.getCommonDialog().dispose();
            }
        }

        @Override
        public void focusGained(FocusEvent e) {
            Object aux = e.getSource();
            if (aux.equals(tfNombre)) {
                tfNombre.selectAll();
            } else if (aux.equals(tfCargo)) {
                tfCargo.selectAll();
            } else if (aux.equals(tfCi)) {
                tfCi.selectAll();
            }
        }

        @Override
        public void focusLost(FocusEvent e) {
        }

        @Override
        public void keyPressed(KeyEvent e) {
            if (e.getKeyCode() == 10) {
                addSave();
            }
        }
    }
}
