INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (1,001,1,'DIRECCION (U.E ARAMASI)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (2,001,2,'CURSO 1 DE PRIMARIA (U.E ARAMASI)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (3,001,3,'CURSO 2 DE PRIMARIA (U.E ARAMASI)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (4,001,4,'CURSO 3 Y 4 DE PRIMARIA (U.E ARAMASI)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (5,001,5,'CURSO 5 DE PRIMARIA (U.E ARAMASI)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (6,001,6,'CURSO 6 DE PRIMARIA (U.E ARAMASI)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (7,001,7,'DEPOSITO (U.E ARAMASI)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (8,001,8,'EDIFICACIONES (U.E. ARAMASI)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (9,001,9,'TERRENOS',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (10,002,1,'DIRECCION (U.E. CORRALON)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (11,002,2,'CURSO 1 DE PRIMARIA  (U.E. CORRALON)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (12,002,3,'CURSO 2 DE PRIMARIA  (U.E. CORRALON)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (13,002,4,'CURSO 3 Y 4 DE PRIMARIA  (U.E. CORRALON)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (14,002,5,'CURSO 5 Y 6 DE PRIMARIA  (U.E. CORRALON)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (15,002,6,'DEPOSITO  (U.E. CORRALON)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (16,002,7,'EDIFICACIONES (U.E. CORRALON)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (17,002,8,'TERRENOS (E.U. CORRALON)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (18,003,1,'CURSO MULTIGRADO (U.E EL PERAL)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (19,003,2,'DORMITORIO PROFESOR (U.E EL PERAL)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (20,003,3,'DEPOSITO (U.E EL PERAL)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (21,003,4,'EDIFICIOS (U.E. EL PERAL)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (22,003,5,'TERRENO (U.E. EL PERAL)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (23,004,1,'CURSO MULTIGRADO  (U.E. H. PAMPA BAJA)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (24,004,2,'SALON MULTIFUNCIONAL  (U.E. H. PAMPA BAJA)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (25,004,3,'DEPOSITO  (U.E. H. PAMPA BAJA)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (26,004,4,'DEPOSITO DE ALIMENTOS  (U.E. H. PAMPA BAJA)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (27,004,5,'EDIFICIOS',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (28,004,6,'TERRENOS',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (29,005,1,'CURSO MULTIGRADO 1,2 Y3 (U.E. LOMAN)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (30,005,2,'CURSO MULTIGRADO 4,5 Y 6 PRIMARIA (U.E. LOMAN)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (31,005,3,'COMEDOR (U.E. LOMAN)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (32,005,4,'EDIFICIOS',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (33,005,5,'TERRENOS',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (34,006,1,'CURSO MULTIGRADO 2 Y 5 DE PRIMARIA (U.E. MACHACA)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (35,006,2,'CURSO MULTIGRADO 3 Y 6 DE PRIMARIA (U.E. MACHACA)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (36,006,3,'BIBLIOTECA (U.E. MACHACA)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (37,006,4,'DEPOSITO (U.E. MACHACA)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (38,006,5,'VIVIENDA PROFESOR A (U.E. MACHACA)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (39,006,6,'VIVIENDA PROFESOR B (U.E. MACHACA)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (40,006,7,'EDIFICIOS (U.E. MACHACA)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (41,006,8,'TERRENO (U.E. MACHACA)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (42,007,1,'AULA 1 (1 y 2 DE PRIMARIA)  (U.E. MISION PAMPA)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (43,007,3,'AULA 3 ( 5 Y 6 PRIMARIA) (U.E. MISION PAMPA)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (44,007,2,'AULA 2 (3 Y 4 DE PRIMARIA) (U.E. MISION PAMPA)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (45,007,4,'DEPOSITO  (U.E. MISION PAMPA)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (46,007,5,'VIVIENDA PROFESOR  (U.E. MISION PAMPA)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (47,007,6,'EDIFICACIONES (U.E. MISION PAMPA)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (48,007,7,'TERRENOS (U.E. MISION PAMPA)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (49,008,1,'CURSO INICIAL (U.E. MOLANI)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (50,008,2,'CURSO 1 Y 3 DE PRIMARIA (U.E. MOLANI)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (51,008,3,'CURSO 2 Y 4 DE PRIMARIA (U.E. MOLANI)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (52,008,4,'CURSO 5 Y 6 DE PRIMARIA (U.E. MOLANI)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (53,008,5,'DIRECCION/DORMITORIO PROFESOR (U.E. MOLANI)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (54,008,6,'VIVIENDA PROFESOR 2 (U.E. MOLANI)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (55,008,7,'BIBLIOTECA/VIVIENDA PROFESOR (U.E. MOLANI)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (56,008,8,'EDIFICACIONES (U.E. MOLANI)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (57,008,9,'TERRENOS (U.E. MOLANI)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (58,009,1,'CURSO MULTIGRADO 1 3 Y 4 DE PRIMARIA (U.E. CHIMORI)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (59,009,2,'VIVIENDA PROFESOR (U.E. CHIMORI)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (60,009,3,'EDIFICIOS (U.E. CHIMORI)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (61,009,4,'TERRENOS (U.E. CHIMORI)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (62,010,1,'CURSO A (1 Y 2 DE PRIMARIA) (U.E. PASOPAYITA)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (63,010,2,'CURSO B 4 Y 5 DE PRIMARIA  (U.E. PASOPAYITA)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (64,010,3,'VIVIENDA PROFESOR (U.E. PASOPAYITA)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (65,010,4,'COMEDOR (U.E. PASOPAYITA)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (66,010,5,'DEPOSITO (U.E. PASOPAYITA)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (67,010,6,'EDIFICIOS',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (68,010,7,'TERRENO',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (69,011,1,'DIRECCION (U.E. RICARDO MUJIA)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (70,011,2,'SECRETARIA (U.E. RICARDO MUJIA)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (71,011,3,'CURSO INICIAL A (U.E. RICARDO MUJIA)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (72,011,4,'CURSO INICIAL B (U.E. RICARDO MUJIA)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (73,011,5,'CURSO 1 DE PRIMARIA A (U.E. RICARDO MUJIA)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (74,011,6,'CURSO 1 DE PRIMARIA B (U.E. RICARDO MUJIA)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (75,011,7,'CURSO 2 DE PRIMARIA A (U.E. RICARDO MUJIA)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (76,011,8,'CURSO 2 DE PRIMARIA B (U.E. RICARDO MUJIA)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (77,011,9,'CURSO 3 DE PRIMARIA A (U.E. RICARDO MUJIA)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (78,011,10,'CURSO 3 DE PRIMARIA B (U.E. RICARDO MUJIA)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (79,011,11,'CURSO 4 DE PRIMARIA A (U.E. RICARDO MUJIA)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (80,011,12,'CURSO 4 DE PRIMARIA B (U.E. RICARDO MUJIA)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (81,011,13,'CURSO 5 DE PRIMARIA A (U.E. RICARDO MUJIA)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (82,011,14,'CURSO 5 DE PRIMARIA B (U.E. RICARDO MUJIA)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (83,011,15,'CURSO 6 PRIMARIA A (U.E. RICARDO MUJIA)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (84,011,16,'CURSO 6 DE PRIMARIA B (U.E. RICARDO MUJIA)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (85,011,17,'SALA DE REUNIONES (U.E. RICARDO MUJIA)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (86,011,18,'SALA DE MUSICA (U.E. RICARDO MUJIA)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (87,011,19,'SALA AUDIOVISUAL (U.E. RICARDO MUJIA)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (88,011,20,'SALA DE PROFESORES (U.E. RICARDO MUJIA)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (89,011,21,'PORTERIA (U.E. RICARDO MUJIA)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (90,011,22,'COCINA (U.E. RICARDO MUJIA)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (91,011,23,'DEPOSITO (U.E. RICARDO MUJIA)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (92,011,24,'EDIFICIOS (U.E.RICARDO MUJIA)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (93,011,25,'TERRENOS (U.E. RICARDO MUJIA)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (94,012,1,'CURSO MULTIGRADO 1 Y 4  (U.E. PUCA PAMPA)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (95,012,2,'CURSO MULTIGRADO 3 Y 6 DE PRIMARIA (U.E. PUCA PAMPA)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (96,012,3,'BIBLIOTECA/DEPOSITO (U.E. PUCA PAMPA)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (97,012,4,'EDIFICIOS',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (98,012,5,'TERRENOS',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (99,013,1,'DIRECCION (U.E. QOCHI)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (100,013,2,'CURSO 3 Y 4 DE PRIMARIA (U.E. QOCHI)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (101,013,3,'CURSO 2 Y 6 DE PRIMARIA (U.E. QOCHI)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (102,013,4,'DEPOSITO (U.E. QOCHI)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (103,013,5,'VIVIENDA PROFESOR (U.E. QOCHI)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (104,013,6,'EDIFICIOS (U.E. QOCHI)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (105,013,7,'TERRENOS (U.E. QOCHI)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (106,014,1,'AULA 1 (U.E. ROSAS PAMPA)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (107,014,2,'AULA 2 (U.E. ROSAS PAMPA)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (108,014,3,'OFICINA DEPOSITO (U.E. ROSAS PAMPA)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (109,014,4,'VIVIENDA PROFESOR (U.E. ROSAS PAMPA)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (110,014,5,'EDIFICACIONES (U.E. ROSAS PAMPA)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (111,014,6,'TERRENOS (U.E. ROSAS PAMPA)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (112,015,1,'EDIFCACIONES (U.E. SAN JOSE DE TOCA)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (113,015,2,'TERRENOS (U.E. SAN JOSE DE TOCA)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (114,016,1,'DIRECCION (U.E. TOMOROCO)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (115,016,2,'CURSO INICIAL 1 Y 2 SECCION (U.E. TOMOROCO)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (116,016,3,'CURSO 1 DE PRIMARIA (U.E. TOMOROCO)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (117,016,4,'CURSO 2 DE PRIMARIA (U.E. TOMOROCO)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (118,016,5,'CURSO 3 DE PRIMARIA (U.E. TOMOROCO)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (119,016,6,'CURSO 4 DE PRIMARIA (U.E. TOMOROCO)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (120,016,7,'CURSO 5 DE PRIMARIA (U.E. TOMOROCO)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (121,016,8,'CURSO 6 DE PRIMARIA (U.E. TOMOROCO)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (122,016,9,'DEPOSITO (U.E. TOMOROCO)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (123,016,10,'EDIFICIOS (U.E TOMOROCO)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (124,016,11,'TERRENOS (U.E. TOMOROCO)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (125,017,1,'CURSO MULTIGRADO 1 Y 3 DE PRIMARIA (U.E. TORCO TORCO)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (126,017,2,'CURSO MULTIGRADO 5 Y 6 DE PRIMARIA (U.E. TORCO TORCO)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (127,017,3,'DEPOSITO (U.E. TORCO TORCO)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (128,017,4,'VIVIENDA PROFESOR (U.E. TORCO TORCO)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (129,017,5,'EDIFICIOS (U.E. TORCO TORCO)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (130,017,6,'TERRENO (U.E. TORCO TORCO)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (131,018,1,'CURSO MULTIGRADO (2 4 Y 6)  (U.E. TRANQAS H. QASA)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (132,018,2,'COMEDOR (U.E. TRANQAS H. QASA)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (133,018,3,'DEPOSITO DE ALIMENTOS (U.E. TRANQAS H. QASA)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (134,018,4,'EDIFICIO (U.E. TRANCAS HORNA QASA)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (135,018,5,'TERRENOS (U.E. TRANCAS HORNO QASA)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (136,019,1,'DIRECCION  (U.E. EL PALMAR)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (137,019,2,'KINDER (U.E. EL PALMAR)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (138,019,3,'CURSO 1 Y 2 DE PRIMARIA (U.E. EL PALMAR)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (139,019,4,'CURSO 3 Y 4 DE PRIMARIA (U.E. EL PALMAR)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (140,019,5,'CURSO 5 DE PRIMARIA (U.E. EL PALMAR)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (141,019,6,'CURSO 6 DE PRIMARIA (U.E. EL PALMAR)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (142,019,7,'EDIFICIO (U.E. EL PALMAR)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (143,019,8,'TERRENOS (U.E. EL PALMAR)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (144,020,1,'DIRECCION (U.E. RODEO EL PALMAR)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (145,020,2,'CURSO INICIAL (U.E. RODEO EL PALMAR)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (146,020,3,'CURSO 1 DE PRIMARIA (U.E. RODEO EL PALMAR)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (147,020,4,'CURSO 2 DE PRIMARIA (U.E. RODEO EL PALMAR)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (148,020,5,'CURSO 3 DE PRIMARIA (U.E. RODEO EL PALMAR)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (149,020,6,'CURSO 4 DE PRIMARIA (U.E. RODEO EL PALMAR)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (150,020,7,'CURSO 5 DE PRIMARIA (U.E. RODEO EL PALMAR)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (151,020,8,'CURSO 6 DE PRIMARIA (U.E. RODEO EL PALMAR)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (152,020,9,'DEPOSITO (U.E. RODEO EL PALMAR)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (153,020,10,'EDIFICIO (U.E: RODEO EL PALMAR)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (154,020,11,'TERRENOS (U.E. RODEO EL PALMAR)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (155,021,1,'DIRECCION (U.E. ELIZARDO PEREZ DE PASOPAYA)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (156,021,2,'SECRETARIA  (U.E. ELIZARDO PEREZ DE PASOPAYA)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (157,021,3,'BIBLIOTECA  (U.E. ELIZARDO PEREZ DE PASOPAYA)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (158,021,4,'CURSO 1 DE  PRIMARIA  (U.E. ELIZARDO PEREZ DE PASOPAYA)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (159,021,5,'CURSO 2�  DE PRIMARIA  (U.E. ELIZARDO PEREZ DE PASOPAYA)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (160,021,6,'"CURSO 3� DE PRIMARIA ""A""  (U.E. ELIZARDO PEREZ DE PASOPAYA)"',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (161,021,7,'"CURSO 3� DE PRIMARIA ""B""  (U.E. ELIZARDO PEREZ DE PASOPAYA)"',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (162,021,8,'CURSO4� DE PRIMARIA  (U.E. ELIZARDO PEREZ DE PASOPAYA)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (163,021,9,'CURSO 5� DE PRIMARIA  (U.E. ELIZARDO PEREZ DE PASOPAYA)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (164,021,10,'CURSO 6� DE PRIMARIA  (U.E. ELIZARDO PEREZ DE PASOPAYA)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (165,021,11,'PORTERIA  (U.E. ELIZARDO PEREZ DE PASOPAYA)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (166,021,12,'DEPOSITO  (U.E. ELIZARDO PEREZ DE PASOPAYA)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (167,021,13,'EDIFICIOS (U.E. ELIZARDO PEREZ DE PASOPAYA)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (168,021,14,'TERRENOS (U.E.ELIZARDO PEREZ DE PASOPAYA)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (169,022,1,'AULA 1 (U.E. H. PAMPA ALTA)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (170,022,2,'VIVIENDA PROFESOR  (U.E. H. PAMPA ALTA)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (171,022,3,'EDIFICIOS (U.E. HUAYLLAPAMPA ALTA)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (172,022,4,'TERRENOS (U.E. HUAYLLAPAMPA ALTA)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (173,023,1,'CURSO MULTIGRADO (2 4 5 Y 6 DE PRIMARIA) (U.E. RUMICANCHA)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (174,023,2,'BIBLIOTECA / DEPOSITO (U.E. RUMICANCHA)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (175,023,3,'DEPOSITO DE ALIMENTOS (U.E. RUMICANCHA)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (176,023,4,'EDIFICIOS (U.E. RUMICANCHA)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (177,023,5,'TERRENOS (U.E. RUMICANCHA)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (178,024,1,'CURSO MULTIFUNCIONAL 2 Y 5 (U.E. SAN LUCAS DE U.)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (179,024,2,'CUARTO PROFESOR (U.E. SAN LUCAS DE U.)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (180,024,3,'EDIFICIOS (U.E. SAN LUCAS DE U�UCURI)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (181,024,4,'TERRENOS (U.E. SAN LUCAS DE U�UCURI)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (182,025,1,'DIRECCION (U.E. COLEGIO 14 DE ENERO)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (183,025,2,'CURSO 1 DE SECUNDARIA A  (U.E. COLEGIO 14 DE ENERO)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (184,025,3,'CURSO 1 DE SECUNDARIA B  (U.E. COLEGIO 14 DE ENERO)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (185,025,4,'CURSO 2 DE SECUNDARIA A  (U.E. COLEGIO 14 DE ENERO)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (186,025,5,'CURSO 3 DE SECUNDARIA A  (U.E. COLEGIO 14 DE ENERO)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (187,025,6,'CURSO 3 DE SECUNDARIA B  (U.E. COLEGIO 14 DE ENERO)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (188,025,7,'CURSO 4 DE SECUNDARIA A  (U.E. COLEGIO 14 DE ENERO)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (189,025,8,'CURSO 5  DE SECUNDARIA A  (U.E. COLEGIO 14 DE ENERO)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (190,025,9,'CURSO 6 DE SECUNDARIA A  (U.E. COLEGIO 14 DE ENERO)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (191,025,10,'GABINETE DE COMPUTACION  (U.E. COLEGIO 14 DE ENERO)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (192,025,11,'DEPOSITO  (U.E. COLEGIO 14 DE ENERO)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (193,025,12,'EDIFICIO (U.E. COL. 14 DE ENERO)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (194,025,13,'TERRENO (U.E. COL. 14 DE ENERO)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (195,026,1,'CURSO 1 2 Y5 DE PRIMARIA (U.E. JOYA EL CHARAL)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (196,026,2,'CURSO 3 4 Y 6 DE PRIMARIA (U.E. JOYA EL CHARAL)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (197,026,3,'DEPOSITO (U.E. JOYA EL CHARAL)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (198,026,4,'EDIFICIO (U.E. JOYA CHARAL)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (199,026,5,'TERRENOS (U.E. JOYA CHARAL)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (200,027,1,'DEPOSITO (U.E. COLEGIO 31 MAYO DE PASOPAYA)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (201,027,2,'GABINETE DE COMPUTACION (U.E. COLEGIO 31 MAYO DE PASOPAYA)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (202,027,3,'EDIFICIO (U.E. COL. 31 DE MAYO DE PASOPAYA)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (203,027,4,'TERRENOS (U.E. COL. 31 DE MAYO PASOPAYA)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (204,028,1,'CURSO 1 DE SECUNDARIA (U.E. COLEGIO TOMOROCO)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (205,028,2,'CURSO 2 DE SECUNDARIA (U.E. COLEGIO TOMOROCO)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (206,028,3,'CURSO 3 DE SECUNDARIA (U.E. COLEGIO TOMOROCO)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (207,028,4,'CURSO 4 DE SECUNDARIA (U.E. COLEGIO TOMOROCO)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (208,028,5,'CURSO 5 DE SECUNDARIA (U.E. COLEGIO TOMOROCO)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (209,028,6,'CURSO 6 DE SECUNDARIA (U.E. COLEGIO TOMOROCO)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (210,028,7,'GABINETE DE INFORMATICA (U.E. COLEGIO TOMOROCO)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (211,028,8,'BIBLIOTECA (U.E. COLEGIO TOMOROCO)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (212,028,9,'DEPOSITO (U.E. COLEGIO TOMOROCO)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (213,028,10,'EDIFICIOS (U.E. COLEGIO ESTABAN V, DE TOMOROCO)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (214,028,11,'TERRENOS (U.E. COL. ESTEBAN V. DE TOMOROCO)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (215,029,1,'UNIDAD DE NUTRICION INTEGRAL UNI (C.S. SANTIAGO PRESTO)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (216,029,2,'SALA DE INTERNACION UNI (BEBES) (C.S. SANTIAGO PRESTO)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (217,029,3,'CONSULTORIO MEDICO UNI (C.S. SANTIAGO PRESTO)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (218,029,4,'SALA DE REUNIONES UNI (C.S. SANTIAGO PRESTO)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (219,029,5,'COCINA UNI (C.S. SANTIAGO PRESTO)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (220,029,6,'DEPOSITO UNI (C.S. SANTIAGO PRESTO)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (221,029,7,'JEFATURA MEDICA SANTIAGO DE PRESTO (C.S. SANTIAGO PRESTO)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (222,029,8,'ADMINISTRACION CENTRO SALUD SANTIAGO DE PRESTO (C.S. SANTIAGO PRE',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (223,029,9,'CONSULTORIO MEDICO 1 (C.S. SANTIAGO PRESTO)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (224,029,10,'CONSULTORIO MEDICO 2 (C.S. SANTIAGO PRESTO)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (225,029,11,'ODONTOLOGIA (C.S. SANTIAGO PRESTO)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (226,029,12,'SALA DE INTERNACION MEDICINA INTERNA (C.S. SANTIAGO PRESTO)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (227,029,13,'SALA DE INTERNACION PEDIATRIA (C.S. SANTIAGO PRESTO)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (228,029,14,'SALA DE INTERNACION MATERNIDAD (C.S. SANTIAGO PRESTO)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (229,029,15,'SALA DE PARTOS (C.S. SANTIAGO PRESTO)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (230,029,16,'ENFERMERIA (C.S. SANTIAGO PRESTO)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (231,029,17,'PROGRAMA AMPLIO DE INMUNIZACION (C.S. SANTIAGO PRESTO)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (232,029,18,'AUDITORIO DE REUNIONES (ASIS) (C.S. SANTIAGO PRESTO)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (233,029,19,'LABORATORIO (C.S. SANTIAGO PRESTO)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (234,029,20,'CUARTO ENFERMERA DE TURNO (C.S. SANTIAGO PRESTO)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (235,029,21,'CUARTO DE PORTERIA (C.S. SANTIAGO PRESTO)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (236,029,22,'CUARTO MEDICO DE TURNO (C.S. SANTIAGO PRESTO)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (237,029,23,'FARMACIA (C.S. SANTIAGO PRESTO)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (238,029,24,'ALMACEN DE FARMACIA (C.S. SANTIAGO PRESTO)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (239,029,25,'COMEDOR CENTRO DE SALUD (C.S. SANTIAGO PRESTO)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (240,029,26,'COCINA CENTRO DE SALUD (C.S. SANTIAGO PRESTO)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (241,029,27,'DEPOSITO CENTRO DE SALUD (C.S. SANTIAGO PRESTO)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (242,029,28,'EDIFICIOS (C.S. SANTIAGO DE PRESTO)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (243,029,29,'TERRENOS (C.S. SANTIAGO DE PRESTO)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (244,030,1,'1� SECCION (U.E. CAMINITO DEL SABER PASOPAYA)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (245,030,2,'2� SECCION (U.E. CAMINITO DEL SABER PASOPAYA)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (246,030,3,'DEPOSITO (U.E. CAMINITO DEL SABER PASOPAYA)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (247,030,4,'EDIFICACIONES (U.E. CAMINITO DEL SABER DE PASOPAYA)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (248,030,5,'TERRENOS (U.E. CAMINITO DEL SABER DE PASOPAYA)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (249,031,1,'CURSO 1 DE PRIMARIA (U.E. SILLANI BAJA)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (250,031,2,'CURSO 3 Y 6 DE PRIMARIA (U.E. SILLANI BAJA)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (251,031,3,'EDIFICIOS (U.E. SILLANI BAJA)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (252,031,4,'TERRENOS (U.E. SILLANI BAJA)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (253,032,1,'CONSULTORIO GENERAL (C.S. VIRGEN ROSARIO H. PAMPA ALTA)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (254,032,2,'ENFERMERIA  (C.S. VIRGEN ROSARIO H. PAMPA ALTA)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (255,032,3,'SALA DE INTERNACION  (C.S. VIRGEN ROSARIO H. PAMPA ALTA)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (256,032,4,'FARMACIA  (C.S. VIRGEN ROSARIO H. PAMPA ALTA)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (257,032,5,'SALA DE PARTO  (C.S. VIRGEN ROSARIO H. PAMPA ALTA)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (258,032,6,'SALA DE ESPERA  (C.S. VIRGEN ROSARIO H. PAMPA ALTA)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (259,032,7,'COCINA  (C.S. VIRGEN ROSARIO H. PAMPA ALTA)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (260,032,8,'DEPOSITO  (C.S. VIRGEN ROSARIO H. PAMPA ALTA)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (261,032,9,'EDIFICIOS (C.S. HUAYLLAPAMPA ALTA)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (262,032,10,'TERRENO (C.S. VIERGEN R. H.PAMPA ALTA)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (263,033,1,'CONSULTORIO GENERAL (C.S. PASOPAYA)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (264,033,2,'ENFERMERIA (C.S. PASOPAYA)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (265,033,3,'FARMACIA (C.S. PASOPAYA)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (266,033,4,'SALA DE MATERNIDAD (C.S. PASOPAYA)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (267,033,5,'SALA DE PARTOS (C.S. PASOPAYA)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (268,033,6,'PASILLO (C.S. PASOPAYA)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (269,033,7,'SALA DE ESPERA (C.S. PASOPAYA)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (270,033,8,'COCINA (C.S. PASOPAYA)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (271,033,9,'CUARTO MEDICO (C.S. PASOPAYA)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (272,033,10,'DEPOSITO (C.S. PASOPAYA)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (273,033,11,'EDIFICIOS (C.S PASOPAYA)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (274,033,12,'TERRENOS (C.S. PASOPAYA)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (275,034,1,'CONSULTORIO MEDICO (C.S RODEO EL PALMAR)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (276,034,2,'ENFERMERIA (C.S. RODEO EL PALMAR)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (277,034,3,'SALA DE PARTOS (C.S RODEO EL PALMAR)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (278,034,4,'SALA DE MATERNIDAD (C.S RODEO EL PALMAR)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (279,034,5,'FARMACIA (C.S. RODEO EL PALMAR)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (280,034,6,'SALA DE COMUNICACIONES (C.S. RODEO EL PALMAR)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (281,034,7,'COCINA (C.S. RODEO EL PALMAR)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (282,034,8,'SALA DE ESPERA (C.S. RODEO EL PALMAR)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (283,034,9,'DEPOSITO (C.S. RODEO EL PALMAR)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (284,034,10,'CUARTO MEDICO (C.S. RODEO EL PALMAR)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (285,034,11,'CUARTO PARA ENFERMERIA (C.S. RODEO EL PALMAR)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (286,034,12,'PAI (C.S. RODEO EL PALMAR)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (287,034,13,'SALA DE REUNIONES (C.S. RODEO EL PALMAR)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (288,034,14,'EDIFICIOS (C.S. RODELO EL PALMAR',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (289,034,15,'TERRENOS (C.S. RODEO EL PALMAR)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (290,035,1,'CONSULTORIO GENERAL  (C.S.SAN ISIDRO DE TOMOROCO)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (291,035,2,'ODONTOLOGIA (C.S.SAN ISIDRO DE TOMOROCO)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (292,035,3,'ENFERMERIA (C.S.SAN ISIDRO DE TOMOROCO)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (293,035,4,'FARMACIA (C.S.SAN ISIDRO DE TOMOROCO)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (294,035,5,'SALA DE PARTOS (C.S.SAN ISIDRO DE TOMOROCO)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (295,035,6,'SALA DE INTERNACION (C.S.SAN ISIDRO DE TOMOROCO)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (296,035,7,'PAI (C.S.SAN ISIDRO DE TOMOROCO)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (297,035,8,'DEPOSITO (C.S.SAN ISIDRO DE TOMOROCO)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (298,035,9,'SALA DE ESPERA (C.S.SAN ISIDRO DE TOMOROCO)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (299,035,10,'COCINA (C.S.SAN ISIDRO DE TOMOROCO)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (300,035,11,'EDIFICIOS (C.S. SAN ISIDRO DE TOMOROCO)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (301,035,12,'TERRENOS (C.S. SAN ISIDRO DE TOMOROCO)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (302,036,1,'CONSULTORIO MEDICO (PUESTO DE SALUD PUNO CKASA)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (303,036,2,'PAI (PUESTO DE SALUD PUNO CKASA)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (304,036,3,'SALA DE INTERNACION (PUESTO DE SALUD PUNO CKASA)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (305,036,4,'SALA DE PARTOS (PUESTO DE SALUD PUNO CKASA)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (306,036,5,'DEPOSITO (PUESTO DE SALUD PUNO CKASA)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (307,036,6,'SALA DE ESPERA (PUESTO DE SALUD PUNO CKASA)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (308,036,7,'EDIFICIO (P.S. PUNO CKASA',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (309,036,8,'TERRENOS (P.S. PUNO CKASA',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (310,037,1,'OFICINA DEL ALCALDE (ADM, CENTRAL)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (311,037,2,'UNIDAD DE TRANSPARENCIA (ADM, CENTRAL)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (312,037,3,'ASESORIA LEGAL (ADM, CENTRAL)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (313,037,4,'OFICINA MAYOR ADMINISTRATIVA (ADM, CENTRAL)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (314,037,5,'PLANIFICACION Y ACTIVOS FIJOS (ADM, CENTRAL)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (315,037,6,'OFICINA DE RECAUDACIONES (ADM, CENTRAL)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (316,037,7,'OFICINA DE CONTABILIDAD (ADM, CENTRAL)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (317,037,8,'DIRECCION ADMINISTRATIVA FINANCIERA (ADM, CENTRAL)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (318,037,9,'SECRETERIA (ADM, CENTRAL)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (319,037,10,'PORTERIA (ADM, CENTRAL)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (320,037,11,'CONCEJO MUNICIPAL (ADM, CENTRAL)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (321,037,12,'ASESORIA DEL CONCEJO MUNICIPAL (ADM, CENTRAL)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (322,037,13,'OFICINA DE LA CARTA ORGANICA (ADM, CENTRAL)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (323,037,14,'OFICINA DE LA DEF. NI�EZ Y ADOLECENCIA (ADM, CENTRAL)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (324,037,15,'OFICINA TECNICA INFRAESTRUCTURA (ADM, CENTRAL)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (325,037,16,'OFICINA DE INFRAESTRUCTURA (ADM, CENTRAL)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (326,037,17,'DESARROLLO PRODUCTIVO Y MEDIO AMBIENTAL (ADM, CENTRAL)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (327,037,18,'OFICINA TEC. DESARROLLO PRODUCTIVO Y MEDIO AMBIENTAL (ADM, CENTRA',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (328,037,19,'OFICINA DE AGUA Y SANEAMIENTO (DESCOM) (ADM, CENTRAL)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (329,037,20,'PROGRAMA NACIONAL DE POST ALFABETIZACION (ADM, CENTRAL)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (330,037,21,'OFICINA DE CONTROL CHAGAS (ADM, CENTRAL)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (331,037,22,'OFICINA DE DIR. C. SOCIAL Y COM. SOCIAL (ADM, CENTRAL)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (332,037,23,'OFICINA DE TV LOCAL (ADM, CENTRAL)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (333,037,24,'OFICINA DE ALMACENES (ADM, CENTRAL)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (334,037,25,'MAESTRANZA (ADM, CENTRAL)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (335,037,26,'CONSEJO MUNICIPAL DE ALIMENTACION (COMAN) (ADM, CENTRAL)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (336,037,27,'EDIFICIOS (ADM. CENTRAL GOBIERNO MUNICIPAL DE PRESTO)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (337,037,28,'TERRENOS (ADM. CENTRAL GOBIERNO MUNICIPAL DE PRESTO',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (338,039,1,'DIRECCION (DIRECCION DISTRITAL EDUCACION PRESTO)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (339,040,1,'DIRECCION (YACHAY WASI PRESTO)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (340,040,2,'SALA MULTIFUNCIONAL (YACHAY WASI PRESTO)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (341,040,3,'DORMITORIO HOMBRES (YACHAY WASI PRESTO)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (342,040,4,'DORMITORIO MUJERES (YACHAY WASI PRESTO)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (343,040,5,'DORMITORIO COORDINADOR (YACHAY WASI PRESTO)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (344,040,6,'DORMITORIO PARA VOLUNTARIADO (YACHAY WASI PRESTO)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (345,040,7,'DORMITORIO EQUIPO TEC. FE Y ALEGRIA (YACHAY WASI PRESTO)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (346,040,8,'COCINA (YACHAY WASI PRESTO)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (347,040,9,'DEPOSITO (YACHAY WASI PRESTO)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (348,040,10,'EDIFICIOS ( YACHAY WASI PRESTO)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (349,040,11,'TERRENOS (YACHAY WASI PRESTO)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (350,041,1,'EDIFICIO (C.P. PRESTO)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (351,041,2,'TERRENO (C.P. PRESTO)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (352,042,1,'BIBLIOTECA CENTRAL (BIBLIOTECA PRESTO)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (353,043,1,'COMANDO POLICIAL',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (354,044,1,'EDIFICIO (C.P. HUAYLLAPAMPA ALTA)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (355,044,2,'TERRENOS (C.P. HUAYLLAPAMPA ALTA)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (356,045,1,'AMBIENTE GENERAL  (C.P.HUAYLLAPAMPA BAJA)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (357,045,2,'EDIFICIO (C.P. HUAYLLAPAMPA BAJA)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (358,045,3,'TERRENOS (C.P. HUAYLLAPAMPA BAJA)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (359,046,1,'DIRECCION (INTERNADO Y. WASI PASOPAYA)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (360,046,2,'VIVIENDA 1 (INTERNADO Y. WASI PASOPAYA)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (361,046,3,'VIVIENDA 2 (INTERNADO Y. WASI PASOPAYA)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (362,046,4,'VIVIENDA 3 (INTERNADO Y. WASI PASOPAYA)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (363,046,5,'DORMITORIO HOMBRES (INTERNADO Y. WASI PASOPAYA)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (364,046,6,'DORMITORIO MUJERES (INTERNADO Y. WASI PASOPAYA)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (365,046,7,'COMEDOR (INTERNADO Y. WASI PASOPAYA)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (366,046,8,'SALA DE ESTUDIO (INTERNADO Y. WASI PASOPAYA)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (367,046,9,'BIBLIOTECA (INTERNADO Y. WASI PASOPAYA)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (368,046,10,'SALA DE TEJIDOS (INTERNADO Y. WASI PASOPAYA)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (369,046,11,'DEPOSITO DE ALIMENTOS (INTERNADO Y. WASI PASOPAYA)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (370,046,12,'COCINA (INTERNADO Y. WASI PASOPAYA)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (371,046,13,'EDIFICIOS (YACHAY WASI PASOPAYA)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (372,046,14,'TERRENOS (YACHAY WASI PASOPAYA)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (373,047,1,'OFICINA CENTRAL (SUB CEA PASOPAYA)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (374,048,1,'DORMITORIO HOMBRES (INTERNADO EL PALMAR)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (375,048,2,'DORMITORIO MUJERES (INTERNADO EL PALMAR)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (376,048,3,'SALA DE ESTUDIO Y COMEDOR (INTERNADO EL PALMAR)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (377,048,4,'EDIFICIO (INTERNADO EL PALMAR)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (378,048,5,'TERRENO (INTERNADO EL PALMAR)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (379,049,1,'CONSULTORIO GENERAL (P.S. EL PALMAR)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (380,049,2,'SALA DE PARTOS (P.S. EL PALMAR)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (381,049,3,'FARMACIA (P.S. EL PALMAR)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (382,049,4,'SALA DE INTERNACION (P.S. EL PALMAR)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (383,049,5,'SALA DE ESPERA (P.S. EL PALMAR)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (384,049,6,'EDIFICIOS (P.S. EL PALMAR)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (385,049,7,'TERRENOS (P.S. EL PALMAR',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (386,050,1,'CURSO A (U.E. CHAROBAMBA)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (387,050,2,'CURSO B (U.E. CHAROBAMBA)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (388,050,3,'EDIFICIO (U.E CHAROBAMBA)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (389,050,4,'TERRENO (U.E. CHAROBAMBA)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (390,051,1,'DIRECCION (INTERNADO RODEO EL PALMAR)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (391,051,2,'SALA DE ESTUDIO (INTERNADO RODEO EL PALMAR)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (392,051,3,'DORMITORIO VARONES (INTERNADO RODEO EL PALMAR)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (393,051,4,'DORMITORIO DE MUJERES (INTERNADO RODEO EL PALMAR)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (394,051,5,'COMEDOR (INTERNADO RODEO EL PALMAR)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (395,051,6,'COCINA (INTERNADO RODEO EL PALMAR)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (396,051,7,'DORMITORIO ADMINISTRADORA  (INTERNADO RODEO EL PALMAR)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (397,051,8,'DORMITORIO COORDINADOR  (INTERNADO RODEO EL PALMAR)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (398,051,9,'DEPOSITO  (INTERNADO RODEO EL PALMAR)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (399,051,10,'EDIFICIO (INTERNADO YACHAY WASI RODEO EL PALMAR)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (400,051,11,'TERRENO (INTERNADO YACHAY WASI RODEO EL PALMAR)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (401,052,1,'CONSULTORIO GENERAL (MINI POSTA ARAMASI)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (402,052,2,'ENFERMERIA (MINI POSTA ARAMASI)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (403,052,3,'SALA DE ESPERA (MINI POSTA ARAMASI)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (404,052,4,'COCINA (MINI POSTA ARAMASI)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (405,052,5,'CUARTO PERSONAL (MINI POSTA ARAMASI)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (406,052,6,'EDIFICIO (MINI POSTA ARAMASI)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (407,052,7,'TERRENOS (MINI POSTA ARAMASI)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (408,053,1,'CONSULTORIO GENERAL (MINI POSTA MOLANI)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (409,053,2,'ENFERMERIA (MINI POSTA MOLANI)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (410,053,3,'SALA DE ESPERA (MINI POSTA MOLANI)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (411,053,4,'COCINA (MINI POSTA MOLANI)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (412,053,5,'DORMITORIO PERSONAL (MINI POSTA MOLANI)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (413,053,6,'EDIFICIO (MINI POSTA LOMAN)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (414,053,7,'TERRENOS (MINI POSTA LOMAN)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (415,054,1,'CONSULTORIO GENERAL (MINI POSTA MOLANI)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (416,054,2,'ENFERMERIA (MINI POSTA MOLANI)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (417,054,3,'SALA DE ESPERA (MINI POSTA MOLANI)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (418,054,4,'COCINA (MINI POSTA MOLANI)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (419,054,5,'CUARTO DE PERSONAL (MINI POSTA MOLANI)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (420,054,6,'EDIFICIO (MINI POSTA MOLANI)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (421,054,7,'TERRENOS (MINI POSTA MOLANI)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (422,055,1,'CONSULTORIO MEDICO (MINI POSTA JOYA EL CHARAL)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (423,055,2,'SALA DE PARTOS (MINI POSTA JOYA EL CHARAL)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (424,055,3,'SALA DE INTERNACION (MINI POSTA JOYA EL CHARAL)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (425,055,4,'SALA DE REUNINOS (MINI POSTA JOYA EL CHARAL)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (426,055,5,'EDIFICIO (MINI POSTA JOYA CHARAL)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (427,055,6,'TERRENOS (MINI POSTA JOYA CHARAL)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (428,057,1,'DIRECCION (YACHAY WASI TOMOROCO)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (429,057,2,'SALA DE ESTUDIO (YACHAY WASI TOMOROCO)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (430,057,3,'DORMITORIO HOMBRES A (YACHAY WASI TOMOROCO)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (431,057,4,'DORMITORIO DE HOMBRES B (YACHAY WASI TOMOROCO)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (432,057,5,'DORMITORIO MUJERES (YACHAY WASI TOMOROCO)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (433,057,6,'CUARTO ADMINISTRADORA (YACHAY WASI TOMOROCO)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (434,057,7,' CUARTO COORDINADOR (YACHAY WASI TOMOROCO)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (435,057,8,'COMEDOR (YACHAY WASI TOMOROCO)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (436,057,9,'COCINA (YACHAY WASI TOMOROCO)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (437,057,10,'DEPOSITO DE ALIMENTOS (YACHAY WASI TOMOROCO)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (438,057,11,'EDIFICIO (YACHAY WASI TOMOROCO)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (439,057,12,'TERRENO (YACHAY WASI TOMOROCO)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (440,058,1,'"AULA ""A"" (CENTRO PAN TIPACKASA)"',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (441,058,2,'"AULA ""B"" (CENTRO PAN TIPACKASA)"',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (442,058,3,'EDIFICIO (C.P. TOMOROCO)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (443,058,4,'TERRENOS (C.P. TOMOROCO)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (444,059,1,'CURSO 1 DE SECUNDARIA B (U.E. COLEGIO RODEO EL PALMAR)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (445,059,2,'CURSO 1 DE SECUNDARIA A (U.E. COLEGIO RODEO EL PALMAR)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (446,059,3,'CURSO 2 DE SECUNDARIA (U.E. COLEGIO RODEO EL PALMAR)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (447,059,4,'CURSO 3 DE SECUNDARIA (U.E. COLEGIO RODEO EL PALMAR)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (448,059,5,'CURSO 4 DE SECUNDARIA (U.E. COLEGIO RODEO EL PALMAR)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (449,059,6,'CURSO 5 DE SECUNDARIA (U.E. COLEGIO RODEO EL PALMAR)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (450,059,7,'CURSO 6 DE SECUNDARIA (U.E. COLEGIO RODEO EL PALMAR)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (451,059,8,'DEPOSITO (U.E. COLEGIO RODEO EL PALMAR)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (452,060,1,'AULA (CENTRO PAN TIPACKASA)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (453,060,2,'EDIFICIOS (CENTRO PAN TIPA CKASA)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (454,060,3,'TERRENOS (CENTRO PAN TIPA CKASA)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (455,061,1,'AULA (CENTRO PAN TAPIRANI)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (456,061,2,'EDIFICION (CENTRO PAN TAPIRANI)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (457,061,3,'TERRENOS (CENTRO PAN TAPIRANI)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (458,062,1,'EDIFICIO (CENTRO PAN PASOPAYA)',NOW(),1);
INSERT INTO oficinas (idOficina,idUnidad,codigoOficina,nombreOficina,fechaRegistroOficina,idUsuario) VALUES (459,062,2,'TERRENOS (CENTRO PAN PASOPAYA)',NOW(),1);
