INSERT INTO unidades (idUnidad,codigoUnidad,descripcionUnidad,ciudadUnidad,idEntidad,estadoUnidad) VALUES (1,001,'UNIDAD EDUCATIVA ARAMASI','PRESTO',1107,false);
INSERT INTO unidades (idUnidad,codigoUnidad,descripcionUnidad,ciudadUnidad,idEntidad,estadoUnidad) VALUES (2,002,'UNIDAD EDUCATIVA CORRALON','PRESTO',1107,false);
INSERT INTO unidades (idUnidad,codigoUnidad,descripcionUnidad,ciudadUnidad,idEntidad,estadoUnidad) VALUES (3,003,'UNIDAD EDUCATIVA EL PERAL','PRESTO',1107,false);
INSERT INTO unidades (idUnidad,codigoUnidad,descripcionUnidad,ciudadUnidad,idEntidad,estadoUnidad) VALUES (4,004,'UNIDAD EDUCATIVA HUAYLLAPAMPA BAJA','PRESTO',1107,false);
INSERT INTO unidades (idUnidad,codigoUnidad,descripcionUnidad,ciudadUnidad,idEntidad,estadoUnidad) VALUES (5,005,'UNIDAD EDUCATIVA LOMAN','PRESTO',1107,false);
INSERT INTO unidades (idUnidad,codigoUnidad,descripcionUnidad,ciudadUnidad,idEntidad,estadoUnidad) VALUES (6,006,'UNIDAD EDUCATIVA MACHACA','PRESTO',1107,false);
INSERT INTO unidades (idUnidad,codigoUnidad,descripcionUnidad,ciudadUnidad,idEntidad,estadoUnidad) VALUES (7,007,'UNIDAD EDUCATIVA MISION PAMPA','PRESTO',1107,false);
INSERT INTO unidades (idUnidad,codigoUnidad,descripcionUnidad,ciudadUnidad,idEntidad,estadoUnidad) VALUES (8,008,'UNIDAD EDUCATIVA MOLANI','PRESTO',1107,false);
INSERT INTO unidades (idUnidad,codigoUnidad,descripcionUnidad,ciudadUnidad,idEntidad,estadoUnidad) VALUES (9,009,'UNIDAD EDUCATIVA CHIMORI','PRESTO',1107,false);
INSERT INTO unidades (idUnidad,codigoUnidad,descripcionUnidad,ciudadUnidad,idEntidad,estadoUnidad) VALUES (10,010,'UNIDAD EDUCATIVA PASOPAYITA','PRESTO',1107,false);
INSERT INTO unidades (idUnidad,codigoUnidad,descripcionUnidad,ciudadUnidad,idEntidad,estadoUnidad) VALUES (11,011,'UNIDAD EDUCATIVA RICARDO MUJIA','PRESTO',1107,false);
INSERT INTO unidades (idUnidad,codigoUnidad,descripcionUnidad,ciudadUnidad,idEntidad,estadoUnidad) VALUES (12,012,'UNIDAD EDUCATICA PUCA PAMPA','PRESTO',1107,false);
INSERT INTO unidades (idUnidad,codigoUnidad,descripcionUnidad,ciudadUnidad,idEntidad,estadoUnidad) VALUES (13,013,'UNIDAD EDUCATIVA QOCHI','PRESTO',1107,false);
INSERT INTO unidades (idUnidad,codigoUnidad,descripcionUnidad,ciudadUnidad,idEntidad,estadoUnidad) VALUES (14,014,'UNIDAD EDUCATIVA ROSAS PAMPA','PRESTO',1107,false);
INSERT INTO unidades (idUnidad,codigoUnidad,descripcionUnidad,ciudadUnidad,idEntidad,estadoUnidad) VALUES (15,015,'UNIDAD EDUCATIVA SAN JOSE DE TOCA','PRESTO',1107,false);
INSERT INTO unidades (idUnidad,codigoUnidad,descripcionUnidad,ciudadUnidad,idEntidad,estadoUnidad) VALUES (16,016,'UNIDAD EDUCATIVA TOMOROCO','PRESTO',1107,false);
INSERT INTO unidades (idUnidad,codigoUnidad,descripcionUnidad,ciudadUnidad,idEntidad,estadoUnidad) VALUES (17,017,'UNIDAD EDUCATIVA TORCO TORCO','PRESTO',1107,false);
INSERT INTO unidades (idUnidad,codigoUnidad,descripcionUnidad,ciudadUnidad,idEntidad,estadoUnidad) VALUES (18,018,'UNIDAD EDUCATIVA TRANCAS HORNO Q ASA','PRESTO',1107,false);
INSERT INTO unidades (idUnidad,codigoUnidad,descripcionUnidad,ciudadUnidad,idEntidad,estadoUnidad) VALUES (19,019,'UNIDAD EDUCATIVA EL PALMAR','PRESTO',1107,false);
INSERT INTO unidades (idUnidad,codigoUnidad,descripcionUnidad,ciudadUnidad,idEntidad,estadoUnidad) VALUES (20,020,'UNIDAD EDUCATIVA RODEO EL PALMAR','PRESTO',1107,false);
INSERT INTO unidades (idUnidad,codigoUnidad,descripcionUnidad,ciudadUnidad,idEntidad,estadoUnidad) VALUES (21,021,'UNIDAD EDUCATIVA ELIZARDO PEREZ DE PASOPAYA','PRESTO',1107,false);
INSERT INTO unidades (idUnidad,codigoUnidad,descripcionUnidad,ciudadUnidad,idEntidad,estadoUnidad) VALUES (22,022,'UNIDAD EDUCATIVA HUAYLLAPAMPA ALTA','PRESTO',1107,false);
INSERT INTO unidades (idUnidad,codigoUnidad,descripcionUnidad,ciudadUnidad,idEntidad,estadoUnidad) VALUES (23,023,'UNIDAD EDUCATICA RUMICANCHA','PRESTO',1107,false);
INSERT INTO unidades (idUnidad,codigoUnidad,descripcionUnidad,ciudadUnidad,idEntidad,estadoUnidad) VALUES (24,024,'UNIDAD EDUCATIVA SAN LUCAS DE U�UCURI','PRESTO',1107,false);
INSERT INTO unidades (idUnidad,codigoUnidad,descripcionUnidad,ciudadUnidad,idEntidad,estadoUnidad) VALUES (25,025,'UNIDAD EDUCATIVA COLEGIO 14 DE ENERO','PRESTO',1107,false);
INSERT INTO unidades (idUnidad,codigoUnidad,descripcionUnidad,ciudadUnidad,idEntidad,estadoUnidad) VALUES (26,026,'UNIDAD EDUCATIVA JOYA CHARAL','PRESTO',1107,false);
INSERT INTO unidades (idUnidad,codigoUnidad,descripcionUnidad,ciudadUnidad,idEntidad,estadoUnidad) VALUES (27,027,'UNIDAD EDUCATIVA COLEGIO 31 DE MAYO DE PASOPAYA','PRESTO',1107,false);
INSERT INTO unidades (idUnidad,codigoUnidad,descripcionUnidad,ciudadUnidad,idEntidad,estadoUnidad) VALUES (28,028,'UNIDAD EDUCATIVA COLEGIO ESTEBAN VASQUEZ DE TOMOROCO','PRESTO',1107,false);
INSERT INTO unidades (idUnidad,codigoUnidad,descripcionUnidad,ciudadUnidad,idEntidad,estadoUnidad) VALUES (29,029,'CENTRO DE SALUD SANTIAGO DE PRESTO','PRESTO',1107,false);
INSERT INTO unidades (idUnidad,codigoUnidad,descripcionUnidad,ciudadUnidad,idEntidad,estadoUnidad) VALUES (30,030,'UNIDAD EDUCATIVA CAMINITO DEL SABER DE PASOPAYA','PRESTO',1107,false);
INSERT INTO unidades (idUnidad,codigoUnidad,descripcionUnidad,ciudadUnidad,idEntidad,estadoUnidad) VALUES (31,031,'UNIDAD EDUCATIVA SILLANI BAJA','PRESTO',1107,false);
INSERT INTO unidades (idUnidad,codigoUnidad,descripcionUnidad,ciudadUnidad,idEntidad,estadoUnidad) VALUES (32,032,'CENTRO DE SALUD VIRGEN DEL ROSARIO DE HUAYLLAPAMPA ALTA','PRESTO',1107,false);
INSERT INTO unidades (idUnidad,codigoUnidad,descripcionUnidad,ciudadUnidad,idEntidad,estadoUnidad) VALUES (33,033,'CENTRO DE SALUD PASOPAYA','PRESTO',1107,false);
INSERT INTO unidades (idUnidad,codigoUnidad,descripcionUnidad,ciudadUnidad,idEntidad,estadoUnidad) VALUES (34,034,'CENTRO DE SALUD RODEO EL PALMAR','PRESTO',1107,false);
INSERT INTO unidades (idUnidad,codigoUnidad,descripcionUnidad,ciudadUnidad,idEntidad,estadoUnidad) VALUES (35,035,'CENTRO DE SALUD SAN ISIDRO DE TOMOROCO','PRESTO',1107,false);
INSERT INTO unidades (idUnidad,codigoUnidad,descripcionUnidad,ciudadUnidad,idEntidad,estadoUnidad) VALUES (36,036,'PUESTO DE SALUD PUNO CKASA','PRESTO',1107,false);
INSERT INTO unidades (idUnidad,codigoUnidad,descripcionUnidad,ciudadUnidad,idEntidad,estadoUnidad) VALUES (37,037,'ADMINISTRACION CENTRAL GOBIERNO MUNICIPAL DE PRESTO','PRESTO',1107,false);
INSERT INTO unidades (idUnidad,codigoUnidad,descripcionUnidad,ciudadUnidad,idEntidad,estadoUnidad) VALUES (38,038,'CEA PRESTO','PRESTO',1107,false);
INSERT INTO unidades (idUnidad,codigoUnidad,descripcionUnidad,ciudadUnidad,idEntidad,estadoUnidad) VALUES (39,039,'DIRECCION DISTRITAL MUNICIPIO DE PRESTO','PRESTO',1107,false);
INSERT INTO unidades (idUnidad,codigoUnidad,descripcionUnidad,ciudadUnidad,idEntidad,estadoUnidad) VALUES (40,040,'YACHAY WASI PRESTO','PRESTO',1107,false);
INSERT INTO unidades (idUnidad,codigoUnidad,descripcionUnidad,ciudadUnidad,idEntidad,estadoUnidad) VALUES (41,041,'CENTRO PAN PRESTO','PRESTO',1107,false);
INSERT INTO unidades (idUnidad,codigoUnidad,descripcionUnidad,ciudadUnidad,idEntidad,estadoUnidad) VALUES (42,042,'BIBLIOTECA PRESTO','PRESTO',1107,false);
INSERT INTO unidades (idUnidad,codigoUnidad,descripcionUnidad,ciudadUnidad,idEntidad,estadoUnidad) VALUES (43,043,'COMANDO DE POLICIA','PRESTO',1107,false);
INSERT INTO unidades (idUnidad,codigoUnidad,descripcionUnidad,ciudadUnidad,idEntidad,estadoUnidad) VALUES (44,044,'CENTRO PAN HUAYLLAPAMPA ALTA','PRESTO',1107,false);
INSERT INTO unidades (idUnidad,codigoUnidad,descripcionUnidad,ciudadUnidad,idEntidad,estadoUnidad) VALUES (45,045,'CENTRO PAN HUAYLLAPAMPA BAJA','PRESTO',1107,false);
INSERT INTO unidades (idUnidad,codigoUnidad,descripcionUnidad,ciudadUnidad,idEntidad,estadoUnidad) VALUES (46,046,'INTERNADO YACHAY WASI PASOPAYA','PRESTO',1107,false);
INSERT INTO unidades (idUnidad,codigoUnidad,descripcionUnidad,ciudadUnidad,idEntidad,estadoUnidad) VALUES (47,047,'SUB CEA PASOPAYA','PRESTO',1107,false);
INSERT INTO unidades (idUnidad,codigoUnidad,descripcionUnidad,ciudadUnidad,idEntidad,estadoUnidad) VALUES (48,048,'INTERNADO EL PALMAR','PRESTO',1107,false);
INSERT INTO unidades (idUnidad,codigoUnidad,descripcionUnidad,ciudadUnidad,idEntidad,estadoUnidad) VALUES (49,049,'PUESTO DE SALUD EL PALMAR','PRESTO',1107,false);
INSERT INTO unidades (idUnidad,codigoUnidad,descripcionUnidad,ciudadUnidad,idEntidad,estadoUnidad) VALUES (50,050,'UNIDAD EDUCATIVA CHAROBAMBA','PRESTO',1107,false);
INSERT INTO unidades (idUnidad,codigoUnidad,descripcionUnidad,ciudadUnidad,idEntidad,estadoUnidad) VALUES (51,051,'INTERNADO YACHAY WASI RODEO EL PALMAR','PRESTO',1107,false);
INSERT INTO unidades (idUnidad,codigoUnidad,descripcionUnidad,ciudadUnidad,idEntidad,estadoUnidad) VALUES (52,052,'MINI POSTA ARAMASI','PRESTO',1107,false);
INSERT INTO unidades (idUnidad,codigoUnidad,descripcionUnidad,ciudadUnidad,idEntidad,estadoUnidad) VALUES (53,053,'MINI POSTA LOMAN','PRESTO',1107,false);
INSERT INTO unidades (idUnidad,codigoUnidad,descripcionUnidad,ciudadUnidad,idEntidad,estadoUnidad) VALUES (54,054,'MINIPOSTA MOLANI','PRESTO',1107,false);
INSERT INTO unidades (idUnidad,codigoUnidad,descripcionUnidad,ciudadUnidad,idEntidad,estadoUnidad) VALUES (55,055,'MINI POSTA JOYA CHARAL','PRESTO',1107,false);
INSERT INTO unidades (idUnidad,codigoUnidad,descripcionUnidad,ciudadUnidad,idEntidad,estadoUnidad) VALUES (56,056,'SUB CEA TOMOROCO','PRESTO',1107,false);
INSERT INTO unidades (idUnidad,codigoUnidad,descripcionUnidad,ciudadUnidad,idEntidad,estadoUnidad) VALUES (57,057,'YACHAY WASI TOMOROCO','PRESTO',1107,false);
INSERT INTO unidades (idUnidad,codigoUnidad,descripcionUnidad,ciudadUnidad,idEntidad,estadoUnidad) VALUES (58,058,'CENTRO PAN TOMOROCO','PRESTO',1107,false);
INSERT INTO unidades (idUnidad,codigoUnidad,descripcionUnidad,ciudadUnidad,idEntidad,estadoUnidad) VALUES (59,059,'COLEGIO RODEO EL PALMAR','PRESTO',1107,false);
INSERT INTO unidades (idUnidad,codigoUnidad,descripcionUnidad,ciudadUnidad,idEntidad,estadoUnidad) VALUES (60,060,'CENTRO PAN TIPA CKASA','PRESTO',1107,false);
INSERT INTO unidades (idUnidad,codigoUnidad,descripcionUnidad,ciudadUnidad,idEntidad,estadoUnidad) VALUES (61,061,'CENTRO PAN TAPIRANI','PRESTO',1107,false);
INSERT INTO unidades (idUnidad,codigoUnidad,descripcionUnidad,ciudadUnidad,idEntidad,estadoUnidad) VALUES (62,062,'CENTRO PAN PASOPAYA','PRESTO',1107,false);
